# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Generated gRPC client and server classes for Collector services."""

import grpc
from google.protobuf import empty_pb2

from wind_hub_core.rpc import collector_pb2 as collector__pb2


class CollectorRuntimeServiceStub:
    def __init__(self, channel):
        self.GetCollectorInfo = channel.unary_unary(
            "/windhub.collector.v1.CollectorRuntimeService/GetCollectorInfo",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=collector__pb2.CollectorInfoResponse.FromString,
        )
        self.GetRuntimeStatus = channel.unary_unary(
            "/windhub.collector.v1.CollectorRuntimeService/GetRuntimeStatus",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=collector__pb2.RuntimeStatusResponse.FromString,
        )
        self.GetMetricsSnapshot = channel.unary_unary(
            "/windhub.collector.v1.CollectorRuntimeService/GetMetricsSnapshot",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=collector__pb2.MetricsSnapshotResponse.FromString,
        )
        self.ListTasks = channel.unary_unary(
            "/windhub.collector.v1.CollectorRuntimeService/ListTasks",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=collector__pb2.ListTasksResponse.FromString,
        )
        self.GetTask = channel.unary_unary(
            "/windhub.collector.v1.CollectorRuntimeService/GetTask",
            request_serializer=collector__pb2.TaskIdRequest.SerializeToString,
            response_deserializer=collector__pb2.TaskSummaryMessage.FromString,
        )
        self.ListTaskInstances = channel.unary_unary(
            "/windhub.collector.v1.CollectorRuntimeService/ListTaskInstances",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=collector__pb2.ListTaskInstancesResponse.FromString,
        )
        self.GetTaskInstance = channel.unary_unary(
            "/windhub.collector.v1.CollectorRuntimeService/GetTaskInstance",
            request_serializer=collector__pb2.InstanceIdRequest.SerializeToString,
            response_deserializer=collector__pb2.TaskInstanceMessage.FromString,
        )
        self.ListDevices = channel.unary_unary(
            "/windhub.collector.v1.CollectorRuntimeService/ListDevices",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=collector__pb2.ListDevicesResponse.FromString,
        )
        self.ListSinks = channel.unary_unary(
            "/windhub.collector.v1.CollectorRuntimeService/ListSinks",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=collector__pb2.ListSinksResponse.FromString,
        )
        self.VerifySink = channel.unary_unary(
            "/windhub.collector.v1.CollectorRuntimeService/VerifySink",
            request_serializer=collector__pb2.SinkRequest.SerializeToString,
            response_deserializer=collector__pb2.SinkOperationResponse.FromString,
        )
        self.WriteTestSink = channel.unary_unary(
            "/windhub.collector.v1.CollectorRuntimeService/WriteTestSink",
            request_serializer=collector__pb2.SinkRequest.SerializeToString,
            response_deserializer=collector__pb2.SinkOperationResponse.FromString,
        )


class CollectorRuntimeServiceServicer:
    async def GetCollectorInfo(self, request, context):
        raise NotImplementedError()

    async def GetRuntimeStatus(self, request, context):
        raise NotImplementedError()

    async def GetMetricsSnapshot(self, request, context):
        raise NotImplementedError()

    async def ListTasks(self, request, context):
        raise NotImplementedError()

    async def GetTask(self, request, context):
        raise NotImplementedError()

    async def ListTaskInstances(self, request, context):
        raise NotImplementedError()

    async def GetTaskInstance(self, request, context):
        raise NotImplementedError()

    async def ListDevices(self, request, context):
        raise NotImplementedError()

    async def ListSinks(self, request, context):
        raise NotImplementedError()

    async def VerifySink(self, request, context):
        raise NotImplementedError()

    async def WriteTestSink(self, request, context):
        raise NotImplementedError()


def add_CollectorRuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetCollectorInfo": grpc.unary_unary_rpc_method_handler(
            servicer.GetCollectorInfo,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=collector__pb2.CollectorInfoResponse.SerializeToString,
        ),
        "GetRuntimeStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetRuntimeStatus,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=collector__pb2.RuntimeStatusResponse.SerializeToString,
        ),
        "GetMetricsSnapshot": grpc.unary_unary_rpc_method_handler(
            servicer.GetMetricsSnapshot,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=collector__pb2.MetricsSnapshotResponse.SerializeToString,
        ),
        "ListTasks": grpc.unary_unary_rpc_method_handler(
            servicer.ListTasks,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=collector__pb2.ListTasksResponse.SerializeToString,
        ),
        "GetTask": grpc.unary_unary_rpc_method_handler(
            servicer.GetTask,
            request_deserializer=collector__pb2.TaskIdRequest.FromString,
            response_serializer=collector__pb2.TaskSummaryMessage.SerializeToString,
        ),
        "ListTaskInstances": grpc.unary_unary_rpc_method_handler(
            servicer.ListTaskInstances,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=collector__pb2.ListTaskInstancesResponse.SerializeToString,
        ),
        "GetTaskInstance": grpc.unary_unary_rpc_method_handler(
            servicer.GetTaskInstance,
            request_deserializer=collector__pb2.InstanceIdRequest.FromString,
            response_serializer=collector__pb2.TaskInstanceMessage.SerializeToString,
        ),
        "ListDevices": grpc.unary_unary_rpc_method_handler(
            servicer.ListDevices,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=collector__pb2.ListDevicesResponse.SerializeToString,
        ),
        "ListSinks": grpc.unary_unary_rpc_method_handler(
            servicer.ListSinks,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=collector__pb2.ListSinksResponse.SerializeToString,
        ),
        "VerifySink": grpc.unary_unary_rpc_method_handler(
            servicer.VerifySink,
            request_deserializer=collector__pb2.SinkRequest.FromString,
            response_serializer=collector__pb2.SinkOperationResponse.SerializeToString,
        ),
        "WriteTestSink": grpc.unary_unary_rpc_method_handler(
            servicer.WriteTestSink,
            request_deserializer=collector__pb2.SinkRequest.FromString,
            response_serializer=collector__pb2.SinkOperationResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "windhub.collector.v1.CollectorRuntimeService",
        rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))


class CollectorControlServiceStub:
    def __init__(self, channel):
        self.StartTask = channel.unary_unary(
            "/windhub.collector.v1.CollectorControlService/StartTask",
            request_serializer=collector__pb2.TaskIdRequest.SerializeToString,
            response_deserializer=collector__pb2.TaskSummaryMessage.FromString,
        )
        self.StopTask = channel.unary_unary(
            "/windhub.collector.v1.CollectorControlService/StopTask",
            request_serializer=collector__pb2.TaskIdRequest.SerializeToString,
            response_deserializer=collector__pb2.TaskSummaryMessage.FromString,
        )
        self.StartTaskInstance = channel.unary_unary(
            "/windhub.collector.v1.CollectorControlService/StartTaskInstance",
            request_serializer=collector__pb2.InstanceIdRequest.SerializeToString,
            response_deserializer=collector__pb2.TaskInstanceMessage.FromString,
        )
        self.StopTaskInstance = channel.unary_unary(
            "/windhub.collector.v1.CollectorControlService/StopTaskInstance",
            request_serializer=collector__pb2.InstanceIdRequest.SerializeToString,
            response_deserializer=collector__pb2.TaskInstanceMessage.FromString,
        )
        self.StartAssignedTasks = channel.unary_unary(
            "/windhub.collector.v1.CollectorControlService/StartAssignedTasks",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=collector__pb2.TaskBatchResultMessage.FromString,
        )
        self.StopAssignedTasks = channel.unary_unary(
            "/windhub.collector.v1.CollectorControlService/StopAssignedTasks",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=collector__pb2.TaskBatchResultMessage.FromString,
        )
        self.ReloadConfig = channel.unary_unary(
            "/windhub.collector.v1.CollectorControlService/ReloadConfig",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=collector__pb2.ReloadResultMessage.FromString,
        )
        self.PrepareConfig = channel.unary_unary(
            "/windhub.collector.v1.CollectorControlService/PrepareConfig",
            request_serializer=collector__pb2.PrepareConfigRequest.SerializeToString,
            response_deserializer=collector__pb2.PrepareConfigResponse.FromString,
        )
        self.ActivateConfig = channel.unary_unary(
            "/windhub.collector.v1.CollectorControlService/ActivateConfig",
            request_serializer=collector__pb2.ActivateConfigRequest.SerializeToString,
            response_deserializer=collector__pb2.ActivateConfigResponse.FromString,
        )
        self.AbortConfig = channel.unary_unary(
            "/windhub.collector.v1.CollectorControlService/AbortConfig",
            request_serializer=collector__pb2.AbortConfigRequest.SerializeToString,
            response_deserializer=collector__pb2.AbortConfigResponse.FromString,
        )


class CollectorControlServiceServicer:
    async def StartTask(self, request, context):
        raise NotImplementedError()

    async def StopTask(self, request, context):
        raise NotImplementedError()

    async def StartTaskInstance(self, request, context):
        raise NotImplementedError()

    async def StopTaskInstance(self, request, context):
        raise NotImplementedError()

    async def StartAssignedTasks(self, request, context):
        raise NotImplementedError()

    async def StopAssignedTasks(self, request, context):
        raise NotImplementedError()

    async def ReloadConfig(self, request, context):
        raise NotImplementedError()

    async def PrepareConfig(self, request, context):
        raise NotImplementedError()

    async def ActivateConfig(self, request, context):
        raise NotImplementedError()

    async def AbortConfig(self, request, context):
        raise NotImplementedError()


def add_CollectorControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "StartTask": grpc.unary_unary_rpc_method_handler(
            servicer.StartTask,
            request_deserializer=collector__pb2.TaskIdRequest.FromString,
            response_serializer=collector__pb2.TaskSummaryMessage.SerializeToString,
        ),
        "StopTask": grpc.unary_unary_rpc_method_handler(
            servicer.StopTask,
            request_deserializer=collector__pb2.TaskIdRequest.FromString,
            response_serializer=collector__pb2.TaskSummaryMessage.SerializeToString,
        ),
        "StartTaskInstance": grpc.unary_unary_rpc_method_handler(
            servicer.StartTaskInstance,
            request_deserializer=collector__pb2.InstanceIdRequest.FromString,
            response_serializer=collector__pb2.TaskInstanceMessage.SerializeToString,
        ),
        "StopTaskInstance": grpc.unary_unary_rpc_method_handler(
            servicer.StopTaskInstance,
            request_deserializer=collector__pb2.InstanceIdRequest.FromString,
            response_serializer=collector__pb2.TaskInstanceMessage.SerializeToString,
        ),
        "StartAssignedTasks": grpc.unary_unary_rpc_method_handler(
            servicer.StartAssignedTasks,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=collector__pb2.TaskBatchResultMessage.SerializeToString,
        ),
        "StopAssignedTasks": grpc.unary_unary_rpc_method_handler(
            servicer.StopAssignedTasks,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=collector__pb2.TaskBatchResultMessage.SerializeToString,
        ),
        "ReloadConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ReloadConfig,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=collector__pb2.ReloadResultMessage.SerializeToString,
        ),
        "PrepareConfig": grpc.unary_unary_rpc_method_handler(
            servicer.PrepareConfig,
            request_deserializer=collector__pb2.PrepareConfigRequest.FromString,
            response_serializer=collector__pb2.PrepareConfigResponse.SerializeToString,
        ),
        "ActivateConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ActivateConfig,
            request_deserializer=collector__pb2.ActivateConfigRequest.FromString,
            response_serializer=collector__pb2.ActivateConfigResponse.SerializeToString,
        ),
        "AbortConfig": grpc.unary_unary_rpc_method_handler(
            servicer.AbortConfig,
            request_deserializer=collector__pb2.AbortConfigRequest.FromString,
            response_serializer=collector__pb2.AbortConfigResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "windhub.collector.v1.CollectorControlService",
        rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))
