# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Generated gRPC client and server classes for CommanderService."""

import grpc
from google.protobuf import empty_pb2

from wind_hub_core.rpc import commander_pb2 as commander__pb2


class CommanderServiceStub:
    """CommanderService client stub."""

    def __init__(self, channel):
        """绑定 gRPC channel 上的 Commander unary RPC。"""
        self.GetStatus = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/GetStatus",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=commander__pb2.CommanderStatusResponse.FromString,
        )
        self.ListDevices = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/ListDevices",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=commander__pb2.ListDevicesResponse.FromString,
        )
        self.PrepareConfig = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/PrepareConfig",
            request_serializer=commander__pb2.PrepareConfigRequest.SerializeToString,
            response_deserializer=commander__pb2.PrepareConfigResponse.FromString,
        )
        self.ActivateConfig = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/ActivateConfig",
            request_serializer=commander__pb2.ActivateConfigRequest.SerializeToString,
            response_deserializer=commander__pb2.ActivateConfigResponse.FromString,
        )
        self.AbortConfig = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/AbortConfig",
            request_serializer=commander__pb2.AbortConfigRequest.SerializeToString,
            response_deserializer=commander__pb2.AbortConfigResponse.FromString,
        )
        self.ReloadConfig = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/ReloadConfig",
            request_serializer=empty_pb2.Empty.SerializeToString,
            response_deserializer=commander__pb2.ReloadConfigResponse.FromString,
        )
        self.ReadPoint = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/ReadPoint",
            request_serializer=commander__pb2.ReadPointRequest.SerializeToString,
            response_deserializer=commander__pb2.PointValueMessage.FromString,
        )
        self.ReadPoints = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/ReadPoints",
            request_serializer=commander__pb2.ReadPointsRequest.SerializeToString,
            response_deserializer=commander__pb2.ReadPointsResponse.FromString,
        )
        self.WritePoint = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/WritePoint",
            request_serializer=commander__pb2.WritePointRequest.SerializeToString,
            response_deserializer=commander__pb2.CommandResultMessage.FromString,
        )
        self.WritePoints = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/WritePoints",
            request_serializer=commander__pb2.WritePointsRequest.SerializeToString,
            response_deserializer=commander__pb2.WritePointsResponse.FromString,
        )
        self.VerifyDevice = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/VerifyDevice",
            request_serializer=commander__pb2.VerifyDeviceRequest.SerializeToString,
            response_deserializer=commander__pb2.DeviceVerifyResponse.FromString,
        )
        self.ResolvePoint = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/ResolvePoint",
            request_serializer=commander__pb2.PointRequest.SerializeToString,
            response_deserializer=commander__pb2.PointVerifyResponse.FromString,
        )
        self.VerifyPoint = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/VerifyPoint",
            request_serializer=commander__pb2.PointRequest.SerializeToString,
            response_deserializer=commander__pb2.PointVerifyResponse.FromString,
        )
        self.VerifyPoints = channel.unary_unary(
            "/windhub.commander.v1.CommanderService/VerifyPoints",
            request_serializer=commander__pb2.VerifyPointsRequest.SerializeToString,
            response_deserializer=commander__pb2.PointsVerifyResponse.FromString,
        )


class CommanderServiceServicer:
    """CommanderService server interface."""

    async def GetStatus(self, request, context):
        raise NotImplementedError()

    async def ListDevices(self, request, context):
        raise NotImplementedError()

    async def PrepareConfig(self, request, context):
        raise NotImplementedError()

    async def ActivateConfig(self, request, context):
        raise NotImplementedError()

    async def AbortConfig(self, request, context):
        raise NotImplementedError()

    async def ReloadConfig(self, request, context):
        raise NotImplementedError()

    async def ReadPoint(self, request, context):
        raise NotImplementedError()

    async def ReadPoints(self, request, context):
        raise NotImplementedError()

    async def WritePoint(self, request, context):
        raise NotImplementedError()

    async def WritePoints(self, request, context):
        raise NotImplementedError()

    async def VerifyDevice(self, request, context):
        raise NotImplementedError()

    async def ResolvePoint(self, request, context):
        raise NotImplementedError()

    async def VerifyPoint(self, request, context):
        raise NotImplementedError()

    async def VerifyPoints(self, request, context):
        raise NotImplementedError()


def add_CommanderServiceServicer_to_server(servicer, server):
    """把 CommanderService servicer 注册到 gRPC server。"""
    rpc_method_handlers = {
        "GetStatus": grpc.unary_unary_rpc_method_handler(
            servicer.GetStatus,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=commander__pb2.CommanderStatusResponse.SerializeToString,
        ),
        "ListDevices": grpc.unary_unary_rpc_method_handler(
            servicer.ListDevices,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=commander__pb2.ListDevicesResponse.SerializeToString,
        ),
        "PrepareConfig": grpc.unary_unary_rpc_method_handler(
            servicer.PrepareConfig,
            request_deserializer=commander__pb2.PrepareConfigRequest.FromString,
            response_serializer=commander__pb2.PrepareConfigResponse.SerializeToString,
        ),
        "ActivateConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ActivateConfig,
            request_deserializer=commander__pb2.ActivateConfigRequest.FromString,
            response_serializer=commander__pb2.ActivateConfigResponse.SerializeToString,
        ),
        "AbortConfig": grpc.unary_unary_rpc_method_handler(
            servicer.AbortConfig,
            request_deserializer=commander__pb2.AbortConfigRequest.FromString,
            response_serializer=commander__pb2.AbortConfigResponse.SerializeToString,
        ),
        "ReloadConfig": grpc.unary_unary_rpc_method_handler(
            servicer.ReloadConfig,
            request_deserializer=empty_pb2.Empty.FromString,
            response_serializer=commander__pb2.ReloadConfigResponse.SerializeToString,
        ),
        "ReadPoint": grpc.unary_unary_rpc_method_handler(
            servicer.ReadPoint,
            request_deserializer=commander__pb2.ReadPointRequest.FromString,
            response_serializer=commander__pb2.PointValueMessage.SerializeToString,
        ),
        "ReadPoints": grpc.unary_unary_rpc_method_handler(
            servicer.ReadPoints,
            request_deserializer=commander__pb2.ReadPointsRequest.FromString,
            response_serializer=commander__pb2.ReadPointsResponse.SerializeToString,
        ),
        "WritePoint": grpc.unary_unary_rpc_method_handler(
            servicer.WritePoint,
            request_deserializer=commander__pb2.WritePointRequest.FromString,
            response_serializer=commander__pb2.CommandResultMessage.SerializeToString,
        ),
        "WritePoints": grpc.unary_unary_rpc_method_handler(
            servicer.WritePoints,
            request_deserializer=commander__pb2.WritePointsRequest.FromString,
            response_serializer=commander__pb2.WritePointsResponse.SerializeToString,
        ),
        "VerifyDevice": grpc.unary_unary_rpc_method_handler(
            servicer.VerifyDevice,
            request_deserializer=commander__pb2.VerifyDeviceRequest.FromString,
            response_serializer=commander__pb2.DeviceVerifyResponse.SerializeToString,
        ),
        "ResolvePoint": grpc.unary_unary_rpc_method_handler(
            servicer.ResolvePoint,
            request_deserializer=commander__pb2.PointRequest.FromString,
            response_serializer=commander__pb2.PointVerifyResponse.SerializeToString,
        ),
        "VerifyPoint": grpc.unary_unary_rpc_method_handler(
            servicer.VerifyPoint,
            request_deserializer=commander__pb2.PointRequest.FromString,
            response_serializer=commander__pb2.PointVerifyResponse.SerializeToString,
        ),
        "VerifyPoints": grpc.unary_unary_rpc_method_handler(
            servicer.VerifyPoints,
            request_deserializer=commander__pb2.VerifyPointsRequest.FromString,
            response_serializer=commander__pb2.PointsVerifyResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "windhub.commander.v1.CommanderService",
        rpc_method_handlers,
    )
    server.add_generic_rpc_handlers((generic_handler,))
