"""Wind Hub 跨进程共享配置模型、解析与加载入口。"""

from wind_hub_core.config.device_resolver import resolve_devices
from wind_hub_core.config.fingerprint import fingerprint_config_set
from wind_hub_core.config.loader import load_config
from wind_hub_core.config.point_table_resolver import resolve_point_tables
from wind_hub_core.config.sinks import SinkConfig, SinkPoint, SinkSource, SinksConfig
from wind_hub_core.config.schema import (
    ADSSystemConfig,
    ApiConfig,
    CollectionTaskConfig,
    Config,
    DeviceConfig,
    DeviceInstanceConfig,
    DeviceInstancesConfig,
    DeviceModelConfig,
    DeviceModelsConfig,
    DevicesConfig,
    DeviceTypeConfig,
    InstanceEndpoint,
    InterfaceConfig,
    PointAddress,
    PointConfig,
    PointPatch,
    PointTableConfig,
    PointTablesConfig,
    ReportingConfig,
    ReportingPoint,
    ResolvedPointTable,
    ResolvedPointTables,
    RuntimeConfig,
    SiteConfig,
    SystemConfig,
    TasksConfig,
    TaskTarget,
    UnitConfig,
    UnitsConfig,
)

__all__ = [
    "ADSSystemConfig",
    "SiteConfig",
    "UnitConfig",
    "UnitsConfig",
    "DeviceTypeConfig",
    "DeviceModelConfig",
    "DeviceModelsConfig",
    "InstanceEndpoint",
    "DeviceInstanceConfig",
    "DeviceInstancesConfig",
    "DeviceConfig",
    "DevicesConfig",
    "PointAddress",
    "PointConfig",
    "PointPatch",
    "PointTableConfig",
    "PointTablesConfig",
    "ResolvedPointTable",
    "ResolvedPointTables",
    "RuntimeConfig",
    "SinkConfig",
    "SinkSource",
    "SinkPoint",
    "SinksConfig",
    "ApiConfig",
    "InterfaceConfig",
    "SystemConfig",
    "TaskTarget",
    "CollectionTaskConfig",
    "TasksConfig",
    "ReportingPoint",
    "ReportingConfig",
    "Config",
    "resolve_devices",
    "resolve_point_tables",
    "load_config",
    "fingerprint_config_set",
]
