"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class ScalarValue(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    BOOL_VALUE_FIELD_NUMBER: _builtins.int
    SINT64_VALUE_FIELD_NUMBER: _builtins.int
    UINT64_VALUE_FIELD_NUMBER: _builtins.int
    DOUBLE_VALUE_FIELD_NUMBER: _builtins.int
    STRING_VALUE_FIELD_NUMBER: _builtins.int
    BYTES_VALUE_FIELD_NUMBER: _builtins.int
    bool_value: _builtins.bool
    sint64_value: _builtins.int
    uint64_value: _builtins.int
    double_value: _builtins.float
    string_value: _builtins.str
    bytes_value: _builtins.bytes
    def __init__(
        self,
        *,
        bool_value: _builtins.bool = ...,
        sint64_value: _builtins.int = ...,
        uint64_value: _builtins.int = ...,
        double_value: _builtins.float = ...,
        string_value: _builtins.str = ...,
        bytes_value: _builtins.bytes = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "bytes_value", b"bytes_value", "double_value", b"double_value", "kind", b"kind", "sint64_value", b"sint64_value", "string_value", b"string_value", "uint64_value", b"uint64_value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["bool_value", b"bool_value", "bytes_value", b"bytes_value", "double_value", b"double_value", "kind", b"kind", "sint64_value", b"sint64_value", "string_value", b"string_value", "uint64_value", b"uint64_value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    _WhichOneofReturnType_kind: _TypeAlias = _typing.Literal["bool_value", "sint64_value", "uint64_value", "double_value", "string_value", "bytes_value"]  # noqa: Y015
    _WhichOneofArgType_kind: _TypeAlias = _typing.Literal["kind", b"kind"]  # noqa: Y015
    def WhichOneof(self, oneof_group: _WhichOneofArgType_kind) -> _WhichOneofReturnType_kind | None: ...

Global___ScalarValue: _TypeAlias = ScalarValue  # noqa: Y015

@_typing.final
class ReadPointRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    POINT_ID_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    point_id: _builtins.str
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        point_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "point_id", b"point_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadPointRequest: _TypeAlias = ReadPointRequest  # noqa: Y015

@_typing.final
class ReadPointsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    POINT_IDS_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    @_builtins.property
    def point_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        point_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "point_ids", b"point_ids"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadPointsRequest: _TypeAlias = ReadPointsRequest  # noqa: Y015

@_typing.final
class PointValueMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    POINT_ID_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    QUALITY_FIELD_NUMBER: _builtins.int
    TIMESTAMP_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    point_id: _builtins.str
    quality: _builtins.str
    source: _builtins.str
    @_builtins.property
    def value(self) -> Global___ScalarValue: ...
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        point_id: _builtins.str = ...,
        value: Global___ScalarValue | None = ...,
        quality: _builtins.str = ...,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        source: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp", "value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "point_id", b"point_id", "quality", b"quality", "source", b"source", "timestamp", b"timestamp", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PointValueMessage: _TypeAlias = PointValueMessage  # noqa: Y015

@_typing.final
class ReadPointsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    VALUES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def values(self) -> _containers.RepeatedCompositeFieldContainer[Global___PointValueMessage]: ...
    def __init__(
        self,
        *,
        values: _abc.Iterable[Global___PointValueMessage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["values", b"values"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ReadPointsResponse: _TypeAlias = ReadPointsResponse  # noqa: Y015

@_typing.final
class WritePointRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMAND_ID_FIELD_NUMBER: _builtins.int
    DEVICE_ID_FIELD_NUMBER: _builtins.int
    POINT_ID_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    TIMEOUT_FIELD_NUMBER: _builtins.int
    command_id: _builtins.str
    device_id: _builtins.str
    point_id: _builtins.str
    timeout: _builtins.float
    @_builtins.property
    def value(self) -> Global___ScalarValue: ...
    def __init__(
        self,
        *,
        command_id: _builtins.str = ...,
        device_id: _builtins.str = ...,
        point_id: _builtins.str = ...,
        value: Global___ScalarValue | None = ...,
        timeout: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command_id", b"command_id", "device_id", b"device_id", "point_id", b"point_id", "timeout", b"timeout", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WritePointRequest: _TypeAlias = WritePointRequest  # noqa: Y015

@_typing.final
class WritePointsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMANDS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def commands(self) -> _containers.RepeatedCompositeFieldContainer[Global___WritePointRequest]: ...
    def __init__(
        self,
        *,
        commands: _abc.Iterable[Global___WritePointRequest] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["commands", b"commands"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WritePointsRequest: _TypeAlias = WritePointsRequest  # noqa: Y015

@_typing.final
class CommandResultMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMMAND_ID_FIELD_NUMBER: _builtins.int
    SUCCESS_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    FINISHED_AT_FIELD_NUMBER: _builtins.int
    command_id: _builtins.str
    success: _builtins.bool
    error: _builtins.str
    @_builtins.property
    def finished_at(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        command_id: _builtins.str = ...,
        success: _builtins.bool = ...,
        error: _builtins.str = ...,
        finished_at: _timestamp_pb2.Timestamp | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["finished_at", b"finished_at"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["command_id", b"command_id", "error", b"error", "finished_at", b"finished_at", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CommandResultMessage: _TypeAlias = CommandResultMessage  # noqa: Y015

@_typing.final
class WritePointsResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RESULTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def results(self) -> _containers.RepeatedCompositeFieldContainer[Global___CommandResultMessage]: ...
    def __init__(
        self,
        *,
        results: _abc.Iterable[Global___CommandResultMessage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["results", b"results"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___WritePointsResponse: _TypeAlias = WritePointsResponse  # noqa: Y015

@_typing.final
class CommanderStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUNNING_FIELD_NUMBER: _builtins.int
    DEVICE_COUNT_FIELD_NUMBER: _builtins.int
    HEALTHY_DEVICES_FIELD_NUMBER: _builtins.int
    ACTIVE_REVISION_FIELD_NUMBER: _builtins.int
    ACTIVE_CONFIG_HASH_FIELD_NUMBER: _builtins.int
    PREPARED_REVISION_FIELD_NUMBER: _builtins.int
    PREPARED_CONFIG_HASH_FIELD_NUMBER: _builtins.int
    running: _builtins.bool
    device_count: _builtins.int
    healthy_devices: _builtins.int
    active_revision: _builtins.str
    active_config_hash: _builtins.str
    prepared_revision: _builtins.str
    prepared_config_hash: _builtins.str
    def __init__(
        self,
        *,
        running: _builtins.bool = ...,
        device_count: _builtins.int = ...,
        healthy_devices: _builtins.int = ...,
        active_revision: _builtins.str = ...,
        active_config_hash: _builtins.str = ...,
        prepared_revision: _builtins.str = ...,
        prepared_config_hash: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_config_hash", b"active_config_hash", "active_revision", b"active_revision", "device_count", b"device_count", "healthy_devices", b"healthy_devices", "prepared_config_hash", b"prepared_config_hash", "prepared_revision", b"prepared_revision", "running", b"running"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CommanderStatusResponse: _TypeAlias = CommanderStatusResponse  # noqa: Y015

@_typing.final
class DeviceSummary(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    HEALTHY_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    protocol: _builtins.str
    host: _builtins.str
    port: _builtins.int
    enabled: _builtins.bool
    healthy: _builtins.bool
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        protocol: _builtins.str = ...,
        host: _builtins.str = ...,
        port: _builtins.int = ...,
        enabled: _builtins.bool = ...,
        healthy: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "enabled", b"enabled", "healthy", b"healthy", "host", b"host", "port", b"port", "protocol", b"protocol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceSummary: _TypeAlias = DeviceSummary  # noqa: Y015

@_typing.final
class ListDevicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICES_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def devices(self) -> _containers.RepeatedCompositeFieldContainer[Global___DeviceSummary]: ...
    def __init__(
        self,
        *,
        devices: _abc.Iterable[Global___DeviceSummary] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["devices", b"devices"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListDevicesResponse: _TypeAlias = ListDevicesResponse  # noqa: Y015

@_typing.final
class PrepareConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REVISION_ID_FIELD_NUMBER: _builtins.int
    CONFIG_HASH_FIELD_NUMBER: _builtins.int
    revision_id: _builtins.str
    config_hash: _builtins.str
    def __init__(
        self,
        *,
        revision_id: _builtins.str = ...,
        config_hash: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_hash", b"config_hash", "revision_id", b"revision_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PrepareConfigRequest: _TypeAlias = PrepareConfigRequest  # noqa: Y015

@_typing.final
class PrepareConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    REVISION_ID_FIELD_NUMBER: _builtins.int
    CONFIG_HASH_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    revision_id: _builtins.str
    config_hash: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        revision_id: _builtins.str = ...,
        config_hash: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_hash", b"config_hash", "revision_id", b"revision_id", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PrepareConfigResponse: _TypeAlias = PrepareConfigResponse  # noqa: Y015

@_typing.final
class ActivateConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REVISION_ID_FIELD_NUMBER: _builtins.int
    revision_id: _builtins.str
    def __init__(
        self,
        *,
        revision_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision_id", b"revision_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActivateConfigRequest: _TypeAlias = ActivateConfigRequest  # noqa: Y015

@_typing.final
class ActivateConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    REVISION_ID_FIELD_NUMBER: _builtins.int
    ACTIVE_CONFIG_HASH_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    revision_id: _builtins.str
    active_config_hash: _builtins.str
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        revision_id: _builtins.str = ...,
        active_config_hash: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_config_hash", b"active_config_hash", "revision_id", b"revision_id", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActivateConfigResponse: _TypeAlias = ActivateConfigResponse  # noqa: Y015

@_typing.final
class AbortConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REVISION_ID_FIELD_NUMBER: _builtins.int
    revision_id: _builtins.str
    def __init__(
        self,
        *,
        revision_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision_id", b"revision_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AbortConfigRequest: _TypeAlias = AbortConfigRequest  # noqa: Y015

@_typing.final
class AbortConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    REVISION_ID_FIELD_NUMBER: _builtins.int
    ABORTED_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    revision_id: _builtins.str
    aborted: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        revision_id: _builtins.str = ...,
        aborted: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aborted", b"aborted", "revision_id", b"revision_id", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AbortConfigResponse: _TypeAlias = AbortConfigResponse  # noqa: Y015

@_typing.final
class VerifyDeviceRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    TIMEOUT_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    timeout: _builtins.float
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        timeout: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "timeout", b"timeout"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VerifyDeviceRequest: _TypeAlias = VerifyDeviceRequest  # noqa: Y015

@_typing.final
class DiagnosticStageMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    OK_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    ok: _builtins.bool
    code: _builtins.str
    severity: _builtins.str
    message: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        ok: _builtins.bool = ...,
        code: _builtins.str = ...,
        severity: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "message", b"message", "name", b"name", "ok", b"ok", "severity", b"severity"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DiagnosticStageMessage: _TypeAlias = DiagnosticStageMessage  # noqa: Y015

@_typing.final
class DeviceVerifyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    HOST_FIELD_NUMBER: _builtins.int
    PORT_FIELD_NUMBER: _builtins.int
    OK_FIELD_NUMBER: _builtins.int
    STAGES_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    protocol: _builtins.str
    host: _builtins.str
    port: _builtins.int
    ok: _builtins.bool
    @_builtins.property
    def stages(self) -> _containers.RepeatedCompositeFieldContainer[Global___DiagnosticStageMessage]: ...
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        protocol: _builtins.str = ...,
        host: _builtins.str = ...,
        port: _builtins.int = ...,
        ok: _builtins.bool = ...,
        stages: _abc.Iterable[Global___DiagnosticStageMessage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "host", b"host", "ok", b"ok", "port", b"port", "protocol", b"protocol", "stages", b"stages"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceVerifyResponse: _TypeAlias = DeviceVerifyResponse  # noqa: Y015

@_typing.final
class PointRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    POINT_ID_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    point_id: _builtins.str
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        point_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "point_id", b"point_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PointRequest: _TypeAlias = PointRequest  # noqa: Y015

@_typing.final
class VerifyPointsRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    POINT_GROUP_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    point_group: _builtins.str
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        point_group: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "point_group", b"point_group"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___VerifyPointsRequest: _TypeAlias = VerifyPointsRequest  # noqa: Y015

@_typing.final
class AddressField(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    @_builtins.property
    def value(self) -> Global___ScalarValue: ...
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: Global___ScalarValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["value", b"value"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AddressField: _TypeAlias = AddressField  # noqa: Y015

@_typing.final
class PointVerifyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    POINT_ID_FIELD_NUMBER: _builtins.int
    VARIABLE_NAME_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    CONFIGURED_ADDRESS_FIELD_NUMBER: _builtins.int
    RESOLVED_ADDRESS_FIELD_NUMBER: _builtins.int
    DATA_TYPE_FIELD_NUMBER: _builtins.int
    SCALE_FIELD_NUMBER: _builtins.int
    OFFSET_FIELD_NUMBER: _builtins.int
    UNIT_FIELD_NUMBER: _builtins.int
    READABLE_FIELD_NUMBER: _builtins.int
    OK_FIELD_NUMBER: _builtins.int
    CODE_FIELD_NUMBER: _builtins.int
    SEVERITY_FIELD_NUMBER: _builtins.int
    RAW_VALUE_FIELD_NUMBER: _builtins.int
    ENGINEERING_VALUE_FIELD_NUMBER: _builtins.int
    QUALITY_FIELD_NUMBER: _builtins.int
    SOURCE_FIELD_NUMBER: _builtins.int
    ERROR_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    point_id: _builtins.str
    variable_name: _builtins.str
    protocol: _builtins.str
    data_type: _builtins.str
    scale: _builtins.float
    offset: _builtins.float
    unit: _builtins.str
    ok: _builtins.bool
    code: _builtins.str
    severity: _builtins.str
    quality: _builtins.str
    source: _builtins.str
    error: _builtins.str
    @_builtins.property
    def configured_address(self) -> _containers.RepeatedCompositeFieldContainer[Global___AddressField]: ...
    @_builtins.property
    def resolved_address(self) -> _containers.RepeatedCompositeFieldContainer[Global___AddressField]: ...
    @_builtins.property
    def readable(self) -> _wrappers_pb2.BoolValue: ...
    @_builtins.property
    def raw_value(self) -> Global___ScalarValue: ...
    @_builtins.property
    def engineering_value(self) -> Global___ScalarValue: ...
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        point_id: _builtins.str = ...,
        variable_name: _builtins.str = ...,
        protocol: _builtins.str = ...,
        configured_address: _abc.Iterable[Global___AddressField] | None = ...,
        resolved_address: _abc.Iterable[Global___AddressField] | None = ...,
        data_type: _builtins.str = ...,
        scale: _builtins.float = ...,
        offset: _builtins.float = ...,
        unit: _builtins.str = ...,
        readable: _wrappers_pb2.BoolValue | None = ...,
        ok: _builtins.bool = ...,
        code: _builtins.str = ...,
        severity: _builtins.str = ...,
        raw_value: Global___ScalarValue | None = ...,
        engineering_value: Global___ScalarValue | None = ...,
        quality: _builtins.str = ...,
        source: _builtins.str = ...,
        error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["engineering_value", b"engineering_value", "raw_value", b"raw_value", "readable", b"readable"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["code", b"code", "configured_address", b"configured_address", "data_type", b"data_type", "device_id", b"device_id", "engineering_value", b"engineering_value", "error", b"error", "offset", b"offset", "ok", b"ok", "point_id", b"point_id", "protocol", b"protocol", "quality", b"quality", "raw_value", b"raw_value", "readable", b"readable", "resolved_address", b"resolved_address", "scale", b"scale", "severity", b"severity", "source", b"source", "unit", b"unit", "variable_name", b"variable_name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PointVerifyResponse: _TypeAlias = PointVerifyResponse  # noqa: Y015

@_typing.final
class PointsVerifyResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    POINT_GROUP_FIELD_NUMBER: _builtins.int
    CHECKED_FIELD_NUMBER: _builtins.int
    PASSED_FIELD_NUMBER: _builtins.int
    FAILED_FIELD_NUMBER: _builtins.int
    OK_FIELD_NUMBER: _builtins.int
    POINTS_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    point_group: _builtins.str
    checked: _builtins.int
    passed: _builtins.int
    failed: _builtins.int
    ok: _builtins.bool
    @_builtins.property
    def points(self) -> _containers.RepeatedCompositeFieldContainer[Global___PointVerifyResponse]: ...
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        point_group: _builtins.str = ...,
        checked: _builtins.int = ...,
        passed: _builtins.int = ...,
        failed: _builtins.int = ...,
        ok: _builtins.bool = ...,
        points: _abc.Iterable[Global___PointVerifyResponse] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["checked", b"checked", "device_id", b"device_id", "failed", b"failed", "ok", b"ok", "passed", b"passed", "point_group", b"point_group", "points", b"points"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PointsVerifyResponse: _TypeAlias = PointsVerifyResponse  # noqa: Y015
