"""IEC 60870-5-104 纯 codec 层。

这里只负责 APCI、ASDU、information object、IOA 和 CP56Time2a 的编码/解码；
不执行网络 I/O、不创建 asyncio task，也不维护连接状态机。协议结构错误统一
转换为 ProtocolError。
"""

from wind_hub_core.protocol.iec104.codec.apci import (
    APDUFrame,
    IFrame,
    SFrame,
    UFrame,
    decode_apdu,
    encode_apdu,
    encode_i_frame,
    encode_s_frame,
    encode_u_frame,
)
from wind_hub_core.protocol.iec104.codec.asdu import (
    ASDU,
    decode_asdu,
    encode_asdu,
)
from wind_hub_core.protocol.iec104.codec.info_objects import (
    CounterInterrogationCommand,
    DoubleCommand,
    DoublePoint,
    DoublePointWithTime,
    InterrogationCommand,
    MeasuredValueNormalized,
    MeasuredValueNormalizedWithTime,
    MeasuredValueScaled,
    MeasuredValueShort,
    MeasuredValueShortWithTime,
    SetpointCommandShort,
    SingleCommand,
    SinglePoint,
    SinglePointWithTime,
    decode_c_ci_na_1,
    decode_c_dc_na_1,
    decode_c_ic_na_1,
    decode_c_sc_na_1,
    decode_c_se_nc_1,
    decode_m_dp_na_1,
    decode_m_dp_tb_1,
    decode_m_me_na_1,
    decode_m_me_nb_1,
    decode_m_me_nc_1,
    decode_m_me_td_1,
    decode_m_me_tf_1,
    decode_m_sp_na_1,
    decode_m_sp_tb_1,
    encode_c_ci_na_1,
    encode_c_dc_na_1,
    encode_c_ic_na_1,
    encode_c_sc_na_1,
    encode_c_se_nc_1,
    encode_m_dp_na_1,
    encode_m_dp_tb_1,
    encode_m_me_na_1,
    encode_m_me_nb_1,
    encode_m_me_nc_1,
    encode_m_me_td_1,
    encode_m_me_tf_1,
    encode_m_sp_na_1,
    encode_m_sp_tb_1,
)
from wind_hub_core.protocol.iec104.codec.ioa import decode_ioa, encode_ioa
from wind_hub_core.protocol.iec104.codec.time import (
    CP56Time2a,
    decode_cp56time2a,
    encode_cp56time2a,
    from_datetime,
    to_datetime,
)
from wind_hub_core.protocol.iec104.codec.types import (
    CauseOfTransmission,
    QualityFlag,
    TypeID,
    UFrameType,
)

__all__ = [
    # types
    "TypeID",
    "CauseOfTransmission",
    "UFrameType",
    "QualityFlag",
    # IOA
    "encode_ioa",
    "decode_ioa",
    # time
    "CP56Time2a",
    "encode_cp56time2a",
    "decode_cp56time2a",
    "from_datetime",
    "to_datetime",
    # information object 数据模型
    "SinglePoint",
    "SinglePointWithTime",
    "DoublePoint",
    "DoublePointWithTime",
    "MeasuredValueNormalized",
    "MeasuredValueNormalizedWithTime",
    "MeasuredValueScaled",
    "MeasuredValueShort",
    "MeasuredValueShortWithTime",
    "SingleCommand",
    "DoubleCommand",
    "SetpointCommandShort",
    "InterrogationCommand",
    "CounterInterrogationCommand",
    # information object codec
    "decode_m_sp_na_1",
    "encode_m_sp_na_1",
    "decode_m_sp_tb_1",
    "encode_m_sp_tb_1",
    "decode_m_dp_na_1",
    "encode_m_dp_na_1",
    "decode_m_dp_tb_1",
    "encode_m_dp_tb_1",
    "decode_m_me_na_1",
    "encode_m_me_na_1",
    "decode_m_me_nb_1",
    "encode_m_me_nb_1",
    "decode_m_me_nc_1",
    "encode_m_me_nc_1",
    "decode_m_me_td_1",
    "encode_m_me_td_1",
    "decode_m_me_tf_1",
    "encode_m_me_tf_1",
    "decode_c_sc_na_1",
    "encode_c_sc_na_1",
    "decode_c_dc_na_1",
    "encode_c_dc_na_1",
    "decode_c_se_nc_1",
    "encode_c_se_nc_1",
    "decode_c_ic_na_1",
    "encode_c_ic_na_1",
    "decode_c_ci_na_1",
    "encode_c_ci_na_1",
    # ASDU
    "ASDU",
    "decode_asdu",
    "encode_asdu",
    # APCI
    "APDUFrame",
    "IFrame",
    "SFrame",
    "UFrame",
    "decode_apdu",
    "encode_apdu",
    "encode_i_frame",
    "encode_s_frame",
    "encode_u_frame",
]
