"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import empty_pb2 as _empty_pb2
from grpc import aio as _aio
from wind_hub_core.rpc import collector_pb2 as _collector_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class CollectorRuntimeServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> CollectorRuntimeServiceAsyncStub: ...
    GetCollectorInfo: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.CollectorInfoResponse]
    GetRuntimeStatus: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.RuntimeStatusResponse]
    GetMetricsSnapshot: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.MetricsSnapshotResponse]
    ListTasks: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.ListTasksResponse]
    GetTask: _grpc.UnaryUnaryMultiCallable[_collector_pb2.TaskIdRequest, _collector_pb2.TaskSummaryMessage]
    ListTaskInstances: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.ListTaskInstancesResponse]
    GetTaskInstance: _grpc.UnaryUnaryMultiCallable[_collector_pb2.InstanceIdRequest, _collector_pb2.TaskInstanceMessage]
    ListDevices: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.ListDevicesResponse]
    ListSinks: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.ListSinksResponse]
    VerifySink: _grpc.UnaryUnaryMultiCallable[_collector_pb2.SinkRequest, _collector_pb2.SinkOperationResponse]
    WriteTestSink: _grpc.UnaryUnaryMultiCallable[_collector_pb2.SinkRequest, _collector_pb2.SinkOperationResponse]
    GetLatestTelemetry: _grpc.UnaryUnaryMultiCallable[_collector_pb2.TelemetryLatestRequest, _collector_pb2.TelemetryLatestResponse]
    GetTelemetryTrend: _grpc.UnaryUnaryMultiCallable[_collector_pb2.TelemetryTrendRequest, _collector_pb2.TelemetryTrendResponse]

@_typing.type_check_only
class CollectorRuntimeServiceAsyncStub(CollectorRuntimeServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    GetCollectorInfo: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.CollectorInfoResponse]  # type: ignore[assignment]
    GetRuntimeStatus: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.RuntimeStatusResponse]  # type: ignore[assignment]
    GetMetricsSnapshot: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.MetricsSnapshotResponse]  # type: ignore[assignment]
    ListTasks: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.ListTasksResponse]  # type: ignore[assignment]
    GetTask: _aio.UnaryUnaryMultiCallable[_collector_pb2.TaskIdRequest, _collector_pb2.TaskSummaryMessage]  # type: ignore[assignment]
    ListTaskInstances: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.ListTaskInstancesResponse]  # type: ignore[assignment]
    GetTaskInstance: _aio.UnaryUnaryMultiCallable[_collector_pb2.InstanceIdRequest, _collector_pb2.TaskInstanceMessage]  # type: ignore[assignment]
    ListDevices: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.ListDevicesResponse]  # type: ignore[assignment]
    ListSinks: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _collector_pb2.ListSinksResponse]  # type: ignore[assignment]
    VerifySink: _aio.UnaryUnaryMultiCallable[_collector_pb2.SinkRequest, _collector_pb2.SinkOperationResponse]  # type: ignore[assignment]
    WriteTestSink: _aio.UnaryUnaryMultiCallable[_collector_pb2.SinkRequest, _collector_pb2.SinkOperationResponse]  # type: ignore[assignment]
    GetLatestTelemetry: _aio.UnaryUnaryMultiCallable[_collector_pb2.TelemetryLatestRequest, _collector_pb2.TelemetryLatestResponse]  # type: ignore[assignment]
    GetTelemetryTrend: _aio.UnaryUnaryMultiCallable[_collector_pb2.TelemetryTrendRequest, _collector_pb2.TelemetryTrendResponse]  # type: ignore[assignment]

class CollectorRuntimeServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def GetCollectorInfo(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.CollectorInfoResponse, _abc.Awaitable[_collector_pb2.CollectorInfoResponse]]: ...

    @_abc_1.abstractmethod
    def GetRuntimeStatus(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.RuntimeStatusResponse, _abc.Awaitable[_collector_pb2.RuntimeStatusResponse]]: ...

    @_abc_1.abstractmethod
    def GetMetricsSnapshot(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.MetricsSnapshotResponse, _abc.Awaitable[_collector_pb2.MetricsSnapshotResponse]]: ...

    @_abc_1.abstractmethod
    def ListTasks(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.ListTasksResponse, _abc.Awaitable[_collector_pb2.ListTasksResponse]]: ...

    @_abc_1.abstractmethod
    def GetTask(
        self,
        request: _collector_pb2.TaskIdRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.TaskSummaryMessage, _abc.Awaitable[_collector_pb2.TaskSummaryMessage]]: ...

    @_abc_1.abstractmethod
    def ListTaskInstances(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.ListTaskInstancesResponse, _abc.Awaitable[_collector_pb2.ListTaskInstancesResponse]]: ...

    @_abc_1.abstractmethod
    def GetTaskInstance(
        self,
        request: _collector_pb2.InstanceIdRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.TaskInstanceMessage, _abc.Awaitable[_collector_pb2.TaskInstanceMessage]]: ...

    @_abc_1.abstractmethod
    def ListDevices(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.ListDevicesResponse, _abc.Awaitable[_collector_pb2.ListDevicesResponse]]: ...

    @_abc_1.abstractmethod
    def ListSinks(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.ListSinksResponse, _abc.Awaitable[_collector_pb2.ListSinksResponse]]: ...

    @_abc_1.abstractmethod
    def VerifySink(
        self,
        request: _collector_pb2.SinkRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.SinkOperationResponse, _abc.Awaitable[_collector_pb2.SinkOperationResponse]]: ...

    @_abc_1.abstractmethod
    def WriteTestSink(
        self,
        request: _collector_pb2.SinkRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.SinkOperationResponse, _abc.Awaitable[_collector_pb2.SinkOperationResponse]]: ...

    @_abc_1.abstractmethod
    def GetLatestTelemetry(
        self,
        request: _collector_pb2.TelemetryLatestRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.TelemetryLatestResponse, _abc.Awaitable[_collector_pb2.TelemetryLatestResponse]]: ...

    @_abc_1.abstractmethod
    def GetTelemetryTrend(
        self,
        request: _collector_pb2.TelemetryTrendRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.TelemetryTrendResponse, _abc.Awaitable[_collector_pb2.TelemetryTrendResponse]]: ...

def add_CollectorRuntimeServiceServicer_to_server(servicer: CollectorRuntimeServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...

class CollectorControlServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> CollectorControlServiceAsyncStub: ...
    ApplyTaskPlacement: _grpc.UnaryUnaryMultiCallable[_collector_pb2.TaskPlacementSnapshotRequest, _collector_pb2.TaskPlacementSnapshotResponse]
    StartTask: _grpc.UnaryUnaryMultiCallable[_collector_pb2.TaskStartRequest, _collector_pb2.TaskSummaryMessage]
    StopTask: _grpc.UnaryUnaryMultiCallable[_collector_pb2.TaskIdRequest, _collector_pb2.TaskSummaryMessage]
    StartTaskInstance: _grpc.UnaryUnaryMultiCallable[_collector_pb2.TaskInstanceStartRequest, _collector_pb2.TaskInstanceMessage]
    StopTaskInstance: _grpc.UnaryUnaryMultiCallable[_collector_pb2.InstanceIdRequest, _collector_pb2.TaskInstanceMessage]
    PrepareConfig: _grpc.UnaryUnaryMultiCallable[_collector_pb2.PrepareConfigRequest, _collector_pb2.PrepareConfigResponse]
    ActivateConfig: _grpc.UnaryUnaryMultiCallable[_collector_pb2.ActivateConfigRequest, _collector_pb2.ActivateConfigResponse]
    AbortConfig: _grpc.UnaryUnaryMultiCallable[_collector_pb2.AbortConfigRequest, _collector_pb2.AbortConfigResponse]

@_typing.type_check_only
class CollectorControlServiceAsyncStub(CollectorControlServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    ApplyTaskPlacement: _aio.UnaryUnaryMultiCallable[_collector_pb2.TaskPlacementSnapshotRequest, _collector_pb2.TaskPlacementSnapshotResponse]  # type: ignore[assignment]
    StartTask: _aio.UnaryUnaryMultiCallable[_collector_pb2.TaskStartRequest, _collector_pb2.TaskSummaryMessage]  # type: ignore[assignment]
    StopTask: _aio.UnaryUnaryMultiCallable[_collector_pb2.TaskIdRequest, _collector_pb2.TaskSummaryMessage]  # type: ignore[assignment]
    StartTaskInstance: _aio.UnaryUnaryMultiCallable[_collector_pb2.TaskInstanceStartRequest, _collector_pb2.TaskInstanceMessage]  # type: ignore[assignment]
    StopTaskInstance: _aio.UnaryUnaryMultiCallable[_collector_pb2.InstanceIdRequest, _collector_pb2.TaskInstanceMessage]  # type: ignore[assignment]
    PrepareConfig: _aio.UnaryUnaryMultiCallable[_collector_pb2.PrepareConfigRequest, _collector_pb2.PrepareConfigResponse]  # type: ignore[assignment]
    ActivateConfig: _aio.UnaryUnaryMultiCallable[_collector_pb2.ActivateConfigRequest, _collector_pb2.ActivateConfigResponse]  # type: ignore[assignment]
    AbortConfig: _aio.UnaryUnaryMultiCallable[_collector_pb2.AbortConfigRequest, _collector_pb2.AbortConfigResponse]  # type: ignore[assignment]

class CollectorControlServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def ApplyTaskPlacement(
        self,
        request: _collector_pb2.TaskPlacementSnapshotRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.TaskPlacementSnapshotResponse, _abc.Awaitable[_collector_pb2.TaskPlacementSnapshotResponse]]: ...

    @_abc_1.abstractmethod
    def StartTask(
        self,
        request: _collector_pb2.TaskStartRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.TaskSummaryMessage, _abc.Awaitable[_collector_pb2.TaskSummaryMessage]]: ...

    @_abc_1.abstractmethod
    def StopTask(
        self,
        request: _collector_pb2.TaskIdRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.TaskSummaryMessage, _abc.Awaitable[_collector_pb2.TaskSummaryMessage]]: ...

    @_abc_1.abstractmethod
    def StartTaskInstance(
        self,
        request: _collector_pb2.TaskInstanceStartRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.TaskInstanceMessage, _abc.Awaitable[_collector_pb2.TaskInstanceMessage]]: ...

    @_abc_1.abstractmethod
    def StopTaskInstance(
        self,
        request: _collector_pb2.InstanceIdRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.TaskInstanceMessage, _abc.Awaitable[_collector_pb2.TaskInstanceMessage]]: ...

    @_abc_1.abstractmethod
    def PrepareConfig(
        self,
        request: _collector_pb2.PrepareConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.PrepareConfigResponse, _abc.Awaitable[_collector_pb2.PrepareConfigResponse]]: ...

    @_abc_1.abstractmethod
    def ActivateConfig(
        self,
        request: _collector_pb2.ActivateConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.ActivateConfigResponse, _abc.Awaitable[_collector_pb2.ActivateConfigResponse]]: ...

    @_abc_1.abstractmethod
    def AbortConfig(
        self,
        request: _collector_pb2.AbortConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_collector_pb2.AbortConfigResponse, _abc.Awaitable[_collector_pb2.AbortConfigResponse]]: ...

def add_CollectorControlServiceServicer_to_server(servicer: CollectorControlServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
