"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import empty_pb2 as _empty_pb2
from grpc import aio as _aio
from wind_hub_core.rpc import commander_pb2 as _commander_pb2
import abc as _abc_1
import grpc as _grpc
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import Self as _Self
else:
    from typing_extensions import Self as _Self

_T = _typing.TypeVar("_T")

class _MaybeAsyncIterator(_abc.AsyncIterator[_T], _abc.Iterator[_T], metaclass=_abc_1.ABCMeta): ...

class _ServicerContext(_grpc.ServicerContext, _aio.ServicerContext):  # type: ignore[misc, type-arg]
    ...

GRPC_GENERATED_VERSION: str
GRPC_VERSION: str

class CommanderServiceStub:
    @_typing.overload
    def __new__(cls, channel: _grpc.Channel) -> _Self: ...
    @_typing.overload
    def __new__(cls, channel: _aio.Channel) -> CommanderServiceAsyncStub: ...
    GetStatus: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _commander_pb2.CommanderStatusResponse]
    ListDevices: _grpc.UnaryUnaryMultiCallable[_empty_pb2.Empty, _commander_pb2.ListDevicesResponse]
    PrepareConfig: _grpc.UnaryUnaryMultiCallable[_commander_pb2.PrepareConfigRequest, _commander_pb2.PrepareConfigResponse]
    ActivateConfig: _grpc.UnaryUnaryMultiCallable[_commander_pb2.ActivateConfigRequest, _commander_pb2.ActivateConfigResponse]
    AbortConfig: _grpc.UnaryUnaryMultiCallable[_commander_pb2.AbortConfigRequest, _commander_pb2.AbortConfigResponse]
    ReadPoint: _grpc.UnaryUnaryMultiCallable[_commander_pb2.ReadPointRequest, _commander_pb2.PointValueMessage]
    ReadPoints: _grpc.UnaryUnaryMultiCallable[_commander_pb2.ReadPointsRequest, _commander_pb2.ReadPointsResponse]
    WritePoint: _grpc.UnaryUnaryMultiCallable[_commander_pb2.WritePointRequest, _commander_pb2.CommandResultMessage]
    WritePoints: _grpc.UnaryUnaryMultiCallable[_commander_pb2.WritePointsRequest, _commander_pb2.WritePointsResponse]
    VerifyDevice: _grpc.UnaryUnaryMultiCallable[_commander_pb2.VerifyDeviceRequest, _commander_pb2.DeviceVerifyResponse]
    ResolvePoint: _grpc.UnaryUnaryMultiCallable[_commander_pb2.PointRequest, _commander_pb2.PointVerifyResponse]
    VerifyPoint: _grpc.UnaryUnaryMultiCallable[_commander_pb2.PointRequest, _commander_pb2.PointVerifyResponse]
    VerifyPoints: _grpc.UnaryUnaryMultiCallable[_commander_pb2.VerifyPointsRequest, _commander_pb2.PointsVerifyResponse]

@_typing.type_check_only
class CommanderServiceAsyncStub(CommanderServiceStub):
    def __init__(self, channel: _aio.Channel) -> None: ...
    GetStatus: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _commander_pb2.CommanderStatusResponse]  # type: ignore[assignment]
    ListDevices: _aio.UnaryUnaryMultiCallable[_empty_pb2.Empty, _commander_pb2.ListDevicesResponse]  # type: ignore[assignment]
    PrepareConfig: _aio.UnaryUnaryMultiCallable[_commander_pb2.PrepareConfigRequest, _commander_pb2.PrepareConfigResponse]  # type: ignore[assignment]
    ActivateConfig: _aio.UnaryUnaryMultiCallable[_commander_pb2.ActivateConfigRequest, _commander_pb2.ActivateConfigResponse]  # type: ignore[assignment]
    AbortConfig: _aio.UnaryUnaryMultiCallable[_commander_pb2.AbortConfigRequest, _commander_pb2.AbortConfigResponse]  # type: ignore[assignment]
    ReadPoint: _aio.UnaryUnaryMultiCallable[_commander_pb2.ReadPointRequest, _commander_pb2.PointValueMessage]  # type: ignore[assignment]
    ReadPoints: _aio.UnaryUnaryMultiCallable[_commander_pb2.ReadPointsRequest, _commander_pb2.ReadPointsResponse]  # type: ignore[assignment]
    WritePoint: _aio.UnaryUnaryMultiCallable[_commander_pb2.WritePointRequest, _commander_pb2.CommandResultMessage]  # type: ignore[assignment]
    WritePoints: _aio.UnaryUnaryMultiCallable[_commander_pb2.WritePointsRequest, _commander_pb2.WritePointsResponse]  # type: ignore[assignment]
    VerifyDevice: _aio.UnaryUnaryMultiCallable[_commander_pb2.VerifyDeviceRequest, _commander_pb2.DeviceVerifyResponse]  # type: ignore[assignment]
    ResolvePoint: _aio.UnaryUnaryMultiCallable[_commander_pb2.PointRequest, _commander_pb2.PointVerifyResponse]  # type: ignore[assignment]
    VerifyPoint: _aio.UnaryUnaryMultiCallable[_commander_pb2.PointRequest, _commander_pb2.PointVerifyResponse]  # type: ignore[assignment]
    VerifyPoints: _aio.UnaryUnaryMultiCallable[_commander_pb2.VerifyPointsRequest, _commander_pb2.PointsVerifyResponse]  # type: ignore[assignment]

class CommanderServiceServicer(metaclass=_abc_1.ABCMeta):
    @_abc_1.abstractmethod
    def GetStatus(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.CommanderStatusResponse, _abc.Awaitable[_commander_pb2.CommanderStatusResponse]]: ...

    @_abc_1.abstractmethod
    def ListDevices(
        self,
        request: _empty_pb2.Empty,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.ListDevicesResponse, _abc.Awaitable[_commander_pb2.ListDevicesResponse]]: ...

    @_abc_1.abstractmethod
    def PrepareConfig(
        self,
        request: _commander_pb2.PrepareConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.PrepareConfigResponse, _abc.Awaitable[_commander_pb2.PrepareConfigResponse]]: ...

    @_abc_1.abstractmethod
    def ActivateConfig(
        self,
        request: _commander_pb2.ActivateConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.ActivateConfigResponse, _abc.Awaitable[_commander_pb2.ActivateConfigResponse]]: ...

    @_abc_1.abstractmethod
    def AbortConfig(
        self,
        request: _commander_pb2.AbortConfigRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.AbortConfigResponse, _abc.Awaitable[_commander_pb2.AbortConfigResponse]]: ...

    @_abc_1.abstractmethod
    def ReadPoint(
        self,
        request: _commander_pb2.ReadPointRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.PointValueMessage, _abc.Awaitable[_commander_pb2.PointValueMessage]]: ...

    @_abc_1.abstractmethod
    def ReadPoints(
        self,
        request: _commander_pb2.ReadPointsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.ReadPointsResponse, _abc.Awaitable[_commander_pb2.ReadPointsResponse]]: ...

    @_abc_1.abstractmethod
    def WritePoint(
        self,
        request: _commander_pb2.WritePointRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.CommandResultMessage, _abc.Awaitable[_commander_pb2.CommandResultMessage]]: ...

    @_abc_1.abstractmethod
    def WritePoints(
        self,
        request: _commander_pb2.WritePointsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.WritePointsResponse, _abc.Awaitable[_commander_pb2.WritePointsResponse]]: ...

    @_abc_1.abstractmethod
    def VerifyDevice(
        self,
        request: _commander_pb2.VerifyDeviceRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.DeviceVerifyResponse, _abc.Awaitable[_commander_pb2.DeviceVerifyResponse]]: ...

    @_abc_1.abstractmethod
    def ResolvePoint(
        self,
        request: _commander_pb2.PointRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.PointVerifyResponse, _abc.Awaitable[_commander_pb2.PointVerifyResponse]]: ...

    @_abc_1.abstractmethod
    def VerifyPoint(
        self,
        request: _commander_pb2.PointRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.PointVerifyResponse, _abc.Awaitable[_commander_pb2.PointVerifyResponse]]: ...

    @_abc_1.abstractmethod
    def VerifyPoints(
        self,
        request: _commander_pb2.VerifyPointsRequest,
        context: _ServicerContext,
    ) -> _typing.Union[_commander_pb2.PointsVerifyResponse, _abc.Awaitable[_commander_pb2.PointsVerifyResponse]]: ...

def add_CommanderServiceServicer_to_server(servicer: CommanderServiceServicer, server: _typing.Union[_grpc.Server, _aio.Server]) -> None: ...
