# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from wind_hub_core.rpc import commander_pb2 as wind__hub__core_dot_rpc_dot_commander__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in wind_hub_core/rpc/commander_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CommanderServiceStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetStatus = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/GetStatus',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.CommanderStatusResponse.FromString,
                _registered_method=True)
        self.ListDevices = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/ListDevices',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.ListDevicesResponse.FromString,
                _registered_method=True)
        self.PrepareConfig = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/PrepareConfig',
                request_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.PrepareConfigRequest.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.PrepareConfigResponse.FromString,
                _registered_method=True)
        self.ActivateConfig = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/ActivateConfig',
                request_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.ActivateConfigRequest.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.ActivateConfigResponse.FromString,
                _registered_method=True)
        self.AbortConfig = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/AbortConfig',
                request_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.AbortConfigRequest.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.AbortConfigResponse.FromString,
                _registered_method=True)
        self.ReadPoint = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/ReadPoint',
                request_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.ReadPointRequest.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointValueMessage.FromString,
                _registered_method=True)
        self.ReadPoints = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/ReadPoints',
                request_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.ReadPointsRequest.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.ReadPointsResponse.FromString,
                _registered_method=True)
        self.WritePoint = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/WritePoint',
                request_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.WritePointRequest.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.CommandResultMessage.FromString,
                _registered_method=True)
        self.WritePoints = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/WritePoints',
                request_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.WritePointsRequest.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.WritePointsResponse.FromString,
                _registered_method=True)
        self.VerifyDevice = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/VerifyDevice',
                request_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.VerifyDeviceRequest.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.DeviceVerifyResponse.FromString,
                _registered_method=True)
        self.ResolvePoint = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/ResolvePoint',
                request_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointRequest.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointVerifyResponse.FromString,
                _registered_method=True)
        self.VerifyPoint = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/VerifyPoint',
                request_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointRequest.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointVerifyResponse.FromString,
                _registered_method=True)
        self.VerifyPoints = channel.unary_unary(
                '/windhub.commander.v1.CommanderService/VerifyPoints',
                request_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.VerifyPointsRequest.SerializeToString,
                response_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointsVerifyResponse.FromString,
                _registered_method=True)


class CommanderServiceServicer:
    """Missing associated documentation comment in .proto file."""

    def GetStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListDevices(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PrepareConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ActivateConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AbortConfig(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReadPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WritePoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WritePoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyDevice(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResolvePoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPoint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def VerifyPoints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CommanderServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.CommanderStatusResponse.SerializeToString,
            ),
            'ListDevices': grpc.unary_unary_rpc_method_handler(
                    servicer.ListDevices,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.ListDevicesResponse.SerializeToString,
            ),
            'PrepareConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.PrepareConfig,
                    request_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.PrepareConfigRequest.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.PrepareConfigResponse.SerializeToString,
            ),
            'ActivateConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ActivateConfig,
                    request_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.ActivateConfigRequest.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.ActivateConfigResponse.SerializeToString,
            ),
            'AbortConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.AbortConfig,
                    request_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.AbortConfigRequest.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.AbortConfigResponse.SerializeToString,
            ),
            'ReadPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPoint,
                    request_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.ReadPointRequest.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointValueMessage.SerializeToString,
            ),
            'ReadPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadPoints,
                    request_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.ReadPointsRequest.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.ReadPointsResponse.SerializeToString,
            ),
            'WritePoint': grpc.unary_unary_rpc_method_handler(
                    servicer.WritePoint,
                    request_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.WritePointRequest.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.CommandResultMessage.SerializeToString,
            ),
            'WritePoints': grpc.unary_unary_rpc_method_handler(
                    servicer.WritePoints,
                    request_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.WritePointsRequest.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.WritePointsResponse.SerializeToString,
            ),
            'VerifyDevice': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyDevice,
                    request_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.VerifyDeviceRequest.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.DeviceVerifyResponse.SerializeToString,
            ),
            'ResolvePoint': grpc.unary_unary_rpc_method_handler(
                    servicer.ResolvePoint,
                    request_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointRequest.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointVerifyResponse.SerializeToString,
            ),
            'VerifyPoint': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPoint,
                    request_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointRequest.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointVerifyResponse.SerializeToString,
            ),
            'VerifyPoints': grpc.unary_unary_rpc_method_handler(
                    servicer.VerifyPoints,
                    request_deserializer=wind__hub__core_dot_rpc_dot_commander__pb2.VerifyPointsRequest.FromString,
                    response_serializer=wind__hub__core_dot_rpc_dot_commander__pb2.PointsVerifyResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'windhub.commander.v1.CommanderService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('windhub.commander.v1.CommanderService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CommanderService:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/GetStatus',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.CommanderStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListDevices(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/ListDevices',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.ListDevicesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PrepareConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/PrepareConfig',
            wind__hub__core_dot_rpc_dot_commander__pb2.PrepareConfigRequest.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.PrepareConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ActivateConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/ActivateConfig',
            wind__hub__core_dot_rpc_dot_commander__pb2.ActivateConfigRequest.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.ActivateConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AbortConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/AbortConfig',
            wind__hub__core_dot_rpc_dot_commander__pb2.AbortConfigRequest.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.AbortConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/ReadPoint',
            wind__hub__core_dot_rpc_dot_commander__pb2.ReadPointRequest.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.PointValueMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReadPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/ReadPoints',
            wind__hub__core_dot_rpc_dot_commander__pb2.ReadPointsRequest.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.ReadPointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WritePoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/WritePoint',
            wind__hub__core_dot_rpc_dot_commander__pb2.WritePointRequest.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.CommandResultMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WritePoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/WritePoints',
            wind__hub__core_dot_rpc_dot_commander__pb2.WritePointsRequest.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.WritePointsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyDevice(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/VerifyDevice',
            wind__hub__core_dot_rpc_dot_commander__pb2.VerifyDeviceRequest.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.DeviceVerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ResolvePoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/ResolvePoint',
            wind__hub__core_dot_rpc_dot_commander__pb2.PointRequest.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.PointVerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPoint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/VerifyPoint',
            wind__hub__core_dot_rpc_dot_commander__pb2.PointRequest.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.PointVerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def VerifyPoints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/windhub.commander.v1.CommanderService/VerifyPoints',
            wind__hub__core_dot_rpc_dot_commander__pb2.VerifyPointsRequest.SerializeToString,
            wind__hub__core_dot_rpc_dot_commander__pb2.PointsVerifyResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
