<script setup lang="ts">
import {computed, reactive, ref} from 'vue'
import {ElMessage,ElMessageBox} from 'element-plus'

type Dev={id:string,type:string,group:string,model:string,protocol:string,host:string,online:boolean}
const menu=ref('Devices')
const types=['Wind Turbine','PCS','BMS']
const groups=[{id:'turbine_ads',type:'Wind Turbine'},{id:'turbine_modbus',type:'Wind Turbine'},{id:'storage_pcs',type:'PCS'}]
const models=[{id:'WTG-ADS-3MW',type:'Wind Turbine',protocol:'ADS',table:'wtg_ads_standard'},{id:'WTG-MODBUS-2MW',type:'Wind Turbine',protocol:'MODBUS',table:'wtg_modbus_standard'},{id:'PCS-MODBUS-A',type:'PCS',protocol:'MODBUS',table:'pcs_modbus_v1'}]
const tables=ref([{id:'wtg_ads_standard',protocol:'ADS',points:612},{id:'wtg_modbus_standard',protocol:'MODBUS',points:438},{id:'pcs_modbus_v1',protocol:'MODBUS',points:186}])
const pgroups=ref(['fast','status','control','electrical','mechanical','monitor'])
const units=['none','%','V','kV','A','kW','MW','kVar','Hz','rpm','m/s','deg','°C','s','ms']
const devices=ref<Dev[]>([])
for(let i=1;i<=48;i++) devices.value.push({id:`wtg-${String(i).padStart(3,'0')}`,type:'Wind Turbine',group:i<25?'turbine_modbus':'turbine_ads',model:i<25?'WTG-MODBUS-2MW':'WTG-ADS-3MW',protocol:i<25?'MODBUS':'ADS',host:i<25?`192.168.100.${100+i}`:`192.168.151.${i}`,online:i!==41})
for(let i=1;i<=8;i++)devices.value.push({id:`pcs-${String(i).padStart(2,'0')}`,type:'PCS',group:'storage_pcs',model:'PCS-MODBUS-A',protocol:'MODBUS',host:`192.168.60.${10+i}`,online:true})
const activeType=ref('Wind Turbine'),activeGroup=ref('turbine_ads'),search=ref('')
const current=computed(()=>devices.value.filter(d=>d.type===activeType.value&&d.group===activeGroup.value&&(!search.value||`${d.id} ${d.host}`.includes(search.value))))
const drawer=ref(false),tab=ref('Overview'),selected=ref<Dev|null>(null),addOpen=ref(false)
const newDev=reactive({id:'',type:'Wind Turbine',group:'turbine_ads',model:'WTG-ADS-3MW',host:''})
function selectType(t:string){activeType.value=t;activeGroup.value=groups.find(g=>g.type===t)?.id||''}
function openDev(d:Dev){selected.value=d;drawer.value=true;tab.value='Overview'}
function add(){const m=models.find(x=>x.id===newDev.model)!;devices.value.push({...newDev,protocol:m.protocol,online:false});addOpen.value=false;ElMessage.success('Device created (mock)')}
async function del(){if(!selected.value)return;await ElMessageBox.confirm(`删除 ${selected.value.id}？\n\n将停止该设备的任务实例；直接引用该设备的任务定义会同时删除；Group 任务保留。`,'Delete Device',{type:'warning',confirmButtonText:'Delete Device & Related Tasks'});devices.value=devices.value.filter(x=>x!==selected.value);drawer.value=false}
const dataPoints=Array.from({length:612},(_,i)=>({id:i===0?'wind_speed':i===1?'grid_active_power':`signal_${String(i+1).padStart(3,'0')}`,value:i===0?'8.42':i===1?'1832':String((i*7)%100),unit:i===0?'m/s':i===1?'kW':'%',group:pgroups.value[i%pgroups.value.length],age:i%19===0?'12 s ago':`${80+(i%8)*37} ms ago`}))
const pq=ref(''),pgroup=ref('All'),pmode=ref('All')
const visibleData=computed(()=>dataPoints.filter(p=>(pgroup.value==='All'||p.group===pgroup.value)&&(!pq.value||p.id.includes(pq.value))).slice(0,120))
const trendFields=ref(['wind_speed','grid_active_power']),fieldOpen=ref(false),feedback=ref(['grid_active_power','control_mode'])
const pointTable=ref('wtg_ads_standard'),pointRows=ref(Array.from({length:80},(_,i)=>({id:`point_${i+1}`,locator:i%2?`.signal_${i+1}`:`0x${(31001+i).toString(16)}`,datatype:i%5?'REAL':'BOOL',groups:[pgroups.value[i%pgroups.value.length]],scale:1,offset:0,unit:i%3?'%':'kW',writable:i%17===0})))
const pointEdit=ref(false),pointDraft=reactive({id:'',locator:'',datatype:'REAL',groups:['fast'],scale:1,offset:0,unit:'none',writable:false})
const protocol=computed(()=>tables.value.find(t=>t.id===pointTable.value)?.protocol||'ADS')
const datatypes=computed(()=>protocol.value==='ADS'?['BOOL','BYTE','WORD','INT','DINT','REAL','LREAL','STRING']:['bool','int16','uint16','int32','uint32','float32','float64'])
const defTab=ref('Device Types')
const tasks=ref([{id:'turbine-fast',target:'turbine_modbus',interval:1,sinks:'redis',enabled:true,runtime:'RUNNING'},{id:'turbine-ads',target:'turbine_ads',interval:1,sinks:'redis, file',enabled:true,runtime:'RUNNING'},{id:'pcs-fast',target:'storage_pcs',interval:1,sinks:'redis',enabled:true,runtime:'STOPPED'}])
const configTab=ref('YAML Editor'),file=ref('devices.yaml'),dirty=ref(true),uploaded=ref(false)
const yaml=ref(`devices:\n  - device_id: wtg-040\n    model: WTG-ADS-3MW\n    device_group: turbine_ads\n    endpoint:\n      host: 192.168.151.40\n    enabled: true`)
const diff=` devices:\n-  host: 192.168.151.41\n+  host: 192.168.151.40\n+  device_id: wtg-042`
function saveApply(){dirty.value=false;ElMessage.success('Saved & Reload applied (mock)')}
</script>

<template><div class="shell">
<aside><div class="brand"><b>WH</b> Wind Hub</div><div class="section">运行</div><button v-for="m in ['Overview','Devices','Definitions','Points','Tasks','Quality']" :class="{active:menu===m}" @click="menu=m">{{m}}</button><div class="section">工程</div><button :class="{active:menu==='Debug'}" @click="menu='Debug'">Debug</button><div class="section">系统</div><button v-for="m in ['Config','Logs']" :class="{active:menu===m}" @click="menu=m">{{m}}</button></aside>
<main><header><b>Wind Hub Admin</b><span>采集系统管理控制台</span><el-tag type="success">RUNNING</el-tag><el-tag type="warning">mock</el-tag></header><section class="content">

<template v-if="menu==='Overview'"><div class="head"><div><h1>Overview</h1><p>Wind Hub 运行状态与采集健康摘要</p></div></div><div class="metrics"><el-card v-for="x in [['Runtime','RUNNING'],['Devices','54 / 56'],['Tasks','12 / 14'],['Acquisition','99.92%'],['Active Errors','2'],['Sinks','3 / 3']]" shadow="never"><small>{{x[0]}}</small><strong>{{x[1]}}</strong></el-card></div><el-card shadow="never"><h3>当前异常</h3><el-table :data="[{level:'ERROR',object:'wtg-041',event:'ADS disconnected'},{level:'WARN',object:'turbine-ads',event:'Interval overrun'}]"><el-table-column prop="level" label="Level"/><el-table-column prop="object" label="Object"/><el-table-column prop="event" label="Event"/></el-table></el-card></template>

<template v-if="menu==='Devices'"><div class="head"><div><h1>Devices</h1><p>设备实例、运行状态、数据与控制</p></div><el-button type="primary" @click="addOpen=true">+ Add Device</el-button></div><el-card shadow="never"><div class="tabs"><button v-for="t in types" :class="{on:activeType===t}" @click="selectType(t)">{{t}} <small>{{devices.filter(d=>d.type===t).length}}</small></button></div><div class="chips"><button v-for="g in groups.filter(x=>x.type===activeType)" :class="{on:activeGroup===g.id}" @click="activeGroup=g.id">{{g.id}} ({{devices.filter(d=>d.group===g.id).length}})</button></div><div class="toolbar"><b>{{activeGroup}}</b><el-input v-model="search" placeholder="Search device ID / IP..." clearable style="width:300px"/></div><el-table :data="current" height="560" @row-click="openDev"><el-table-column prop="id" label="Device"/><el-table-column prop="model" label="Model"/><el-table-column prop="protocol" label="Protocol"/><el-table-column prop="host" label="Endpoint"/><el-table-column label="Status"><template #default="s"><el-tag :type="s.row.online?'success':'danger'">{{s.row.online?'Online':'Offline'}}</el-tag></template></el-table-column></el-table></el-card>
<el-dialog v-model="addOpen" title="Add Device" width="680"><el-form label-position="top"><div class="grid"><el-form-item label="Device ID"><el-input v-model="newDev.id"/></el-form-item><el-form-item label="Type"><el-select v-model="newDev.type" @change="selectType(newDev.type);newDev.group=groups.find(g=>g.type===newDev.type)?.id||'';newDev.model=models.find(m=>m.type===newDev.type)?.id||''"><el-option v-for="t in types" :label="t" :value="t"/></el-select></el-form-item><el-form-item label="Group"><el-select v-model="newDev.group"><el-option v-for="g in groups.filter(x=>x.type===newDev.type)" :label="g.id" :value="g.id"/></el-select></el-form-item><el-form-item label="Model"><el-select v-model="newDev.model"><el-option v-for="m in models.filter(x=>x.type===newDev.type)" :label="m.id" :value="m.id"/></el-select></el-form-item><el-form-item label="Host"><el-input v-model="newDev.host"/></el-form-item></div></el-form><template #footer><el-button @click="addOpen=false">Cancel</el-button><el-button type="primary" @click="add">Create</el-button></template></el-dialog>
<el-drawer v-model="drawer" size="68%" :title="selected?.id"><template v-if="selected"><div class="devhead"><div><h2>{{selected.id}} <el-tag :type="selected.online?'success':'danger'">{{selected.online?'Online':'Offline'}}</el-tag></h2><p>{{selected.model}} · {{selected.protocol}} · {{selected.host}}</p></div><el-tag type="success">Applied</el-tag></div><el-tabs v-model="tab"><el-tab-pane label="Overview" name="Overview"><div class="detail"><div v-for="x in [['Type',selected.type],['Group',selected.group],['Model',selected.model],['Protocol',selected.protocol],['Host',selected.host],['Status',selected.online?'Connected':'Disconnected']]"><small>{{x[0]}}</small><b>{{x[1]}}</b></div></div></el-tab-pane><el-tab-pane label="Config" name="Config"><div class="right"><el-button>Edit</el-button><el-button type="danger" plain @click="del">Delete Device</el-button></div><pre>device_id: {{selected.id}}\nmodel: {{selected.model}}\ndevice_group: {{selected.group}}\nendpoint:\n  host: {{selected.host}}</pre></el-tab-pane>
<el-tab-pane label="Data" name="Data"><div class="toolbar"><div><b>612 points</b> <span>· Last update 15:52:31.428</span></div><div class="row"><el-input v-model="pq" placeholder="Search point / variable / description..." style="width:290px"/><el-segmented v-model="pmode" :options="['All','Updated','Writable']"/></div></div><div class="chips"><button v-for="g in ['All',...pgroups]" :class="{on:pgroup===g}" @click="pgroup=g">{{g}}</button></div><el-table :data="visibleData" height="500"><el-table-column prop="id" label="Point"/><el-table-column prop="value" label="Value"/><el-table-column prop="unit" label="Unit"/><el-table-column prop="age" label="Last Update"/></el-table><p>原型按 600+ 点设计；正式实现使用虚拟表格。</p></el-tab-pane>
<el-tab-pane label="Trend" name="Trend"><div class="toolbar"><div><el-button @click="fieldOpen=true">Select Fields</el-button> <span>{{trendFields.length}} selected · Last update 15:52:31.428</span></div><el-segmented :model-value="'Real-time'" :options="['Real-time','5 min','15 min','1 h']"/></div><div class="tags"><el-tag v-for="f in trendFields" closable @close="trendFields=trendFields.filter(x=>x!==f)">{{f}}</el-tag></div><div class="chart"><div v-for="(f,i) in trendFields" class="fake-line" :style="{top:(40+i*42)+'px'}">{{f}} ─────╱───╲────╱────</div></div></el-tab-pane>
<el-tab-pane label="Control" name="Control"><div class="control"><section><h3>Command</h3><el-form label-position="top"><el-form-item label="Writable Point"><el-select model-value="remote_power_demand"><el-option label="remote_power_demand" value="remote_power_demand"/></el-select></el-form-item><el-form-item label="Current Value"><el-input model-value="1800 kW" disabled/></el-form-item><p>Last update: 15:52:31.428</p><el-form-item label="Target Value"><el-input-number :model-value="1600" style="width:100%"/></el-form-item><el-button type="primary" style="width:100%">Send Command</el-button></el-form></section><section><h3>Feedback</h3><div v-for="f in feedback" class="feedback"><span>{{f}}</span><b>{{f.includes('power')?'1798 kW':'Remote'}}</b><span>120 ms ago</span></div></section></div></el-tab-pane></el-tabs></template></el-drawer>
<el-dialog v-model="fieldOpen" title="Select Trend Fields" width="700"><el-checkbox-group v-model="trendFields" class="picker"><el-checkbox v-for="p in dataPoints.slice(0,80)" :value="p.id" :disabled="trendFields.length>=10&&!trendFields.includes(p.id)">{{p.id}} <small>· {{p.group}}</small></el-checkbox></el-checkbox-group><template #footer>最多 10 个字段 <el-button type="primary" @click="fieldOpen=false">Done</el-button></template></el-dialog></template>

<template v-if="menu==='Definitions'"><div class="head"><div><h1>Definitions</h1><p>设备与点表相关的 Meta / Prototype 定义</p></div></div><el-card shadow="never"><el-tabs v-model="defTab"><el-tab-pane label="Device Types" name="Device Types"><div class="right"><el-button type="primary">+ New Type</el-button></div><el-table :data="types.map(x=>({id:x.toLowerCase().replaceAll(' ','_'),name:x}))"><el-table-column prop="id" label="ID"/><el-table-column prop="name" label="Name"/><el-table-column label="References"><template #default="s">{{models.filter(m=>m.type===s.row.name).length}} models · {{groups.filter(g=>g.type===s.row.name).length}} groups</template></el-table-column></el-table></el-tab-pane><el-tab-pane label="Device Groups" name="Device Groups"><div class="right"><el-button type="primary">+ New Group</el-button></div><el-table :data="groups"><el-table-column prop="id" label="Group ID"/><el-table-column prop="type" label="Device Type"/><el-table-column label="References"><template #default>devices / tasks</template></el-table-column></el-table></el-tab-pane><el-tab-pane label="Device Models" name="Device Models"><div class="right"><el-button type="primary">+ New Model</el-button></div><el-table :data="models"><el-table-column prop="id" label="Model ID"/><el-table-column prop="type" label="Device Type"/><el-table-column prop="protocol" label="Protocol"/><el-table-column prop="table" label="Point Table"/></el-table></el-tab-pane><el-tab-pane label="Point Tables" name="Point Tables"><div class="right"><el-button type="primary">+ New Point Table</el-button></div><el-table :data="tables"><el-table-column prop="id" label="Table ID"/><el-table-column prop="protocol" label="Protocol"/><el-table-column prop="points" label="Points"/></el-table></el-tab-pane><el-tab-pane label="Point Groups" name="Point Groups"><div class="right"><el-button type="primary">+ New Point Group</el-button></div><el-table :data="pgroups.map(x=>({id:x,name:x}))"><el-table-column prop="id" label="Group ID"/><el-table-column prop="name" label="Name"/></el-table></el-tab-pane></el-tabs></el-card></template>

<template v-if="menu==='Points'"><div class="head"><div><h1>Points</h1><p>编辑 Point Table 内的具体点定义</p></div><div><el-button>Save</el-button> <el-button type="primary" @click="saveApply">Save & Apply</el-button></div></div><el-card shadow="never"><div class="toolbar"><div class="row"><b>Point Table</b><el-select v-model="pointTable" style="width:240px"><el-option v-for="t in tables" :label="t.id" :value="t.id"/></el-select><el-tag>{{protocol}}</el-tag><span>{{tables.find(t=>t.id===pointTable)?.points}} points</span></div><el-button type="primary" @click="pointEdit=true">+ Add Point</el-button></div><el-table :data="pointRows" height="590"><el-table-column prop="id" label="Point"/><el-table-column prop="locator" :label="protocol==='ADS'?'Symbol / Index':'Address / Function'"/><el-table-column prop="datatype" label="Data Type"/><el-table-column label="Groups"><template #default="s"><el-tag v-for="g in s.row.groups">{{g}}</el-tag></template></el-table-column><el-table-column prop="scale" label="Scale"/><el-table-column prop="offset" label="Offset"/><el-table-column prop="unit" label="Unit"/><el-table-column prop="writable" label="Writable"/></el-table></el-card><el-dialog v-model="pointEdit" title="Add Point" width="760"><el-form label-position="top"><div class="grid"><el-form-item label="Point ID"><el-input v-model="pointDraft.id"/></el-form-item><el-form-item :label="protocol==='ADS'?'ADS Symbol / Index':'Modbus Address / Function'"><el-input v-model="pointDraft.locator"/></el-form-item><el-form-item label="Data Type"><el-select v-model="pointDraft.datatype"><el-option v-for="x in datatypes" :label="x" :value="x"/></el-select></el-form-item><el-form-item label="Point Groups"><el-select v-model="pointDraft.groups" multiple><el-option v-for="g in pgroups" :label="g" :value="g"/></el-select></el-form-item><el-form-item label="Scale"><el-input-number v-model="pointDraft.scale"/></el-form-item><el-form-item label="Offset"><el-input-number v-model="pointDraft.offset"/></el-form-item><el-form-item label="Unit"><el-select v-model="pointDraft.unit"><el-option v-for="u in units" :label="u" :value="u"/></el-select></el-form-item><el-form-item label="Writable"><el-switch v-model="pointDraft.writable"/></el-form-item></div></el-form><template #footer><el-button @click="pointEdit=false">Cancel</el-button><el-button type="primary">Save</el-button></template></el-dialog></template>

<template v-if="menu==='Tasks'"><div class="head"><div><h1>Tasks</h1><p>采集任务定义与运行控制</p></div><el-button type="primary">+ New Task</el-button></div><el-card shadow="never"><el-table :data="tasks"><el-table-column prop="id" label="Task"/><el-table-column prop="target" label="Target"/><el-table-column prop="interval" label="Interval(s)"/><el-table-column prop="sinks" label="Sinks"/><el-table-column prop="enabled" label="Enabled"/><el-table-column prop="runtime" label="Runtime"/><el-table-column label="Actions"><template #default><el-button size="small">Stop</el-button><el-button size="small">Edit</el-button><el-button size="small" type="danger" plain>Delete</el-button></template></el-table-column></el-table></el-card></template>

<template v-if="menu==='Config'"><div class="head"><div><h1>Config</h1><p>直接编辑 YAML、上传配置、Diff 与下发生效</p></div></div><el-card shadow="never"><el-tabs v-model="configTab"><el-tab-pane label="YAML Editor" name="YAML Editor"><div class="config"><div class="files"><button v-for="f in ['system.yaml','units.yaml','device_models.yaml','points.yaml','devices.yaml','tasks.yaml','reporting.yaml']" :class="{on:file===f}" @click="file=f">{{f}}</button></div><div><div class="toolbar"><b>{{file}}</b><el-tag :type="dirty?'warning':'success'">{{dirty?'Pending Apply':'Applied'}}</el-tag></div><el-input v-model="yaml" type="textarea" :rows="21"/><div class="right"><el-button>Validate</el-button><el-button>Save</el-button><el-button type="primary" @click="saveApply">Save & Apply</el-button></div></div><div><h3>Diff</h3><pre>{{diff}}</pre></div></div></el-tab-pane><el-tab-pane label="Upload" name="Upload"><div class="upload"><section><h3>Upload Configuration File</h3><el-select v-model="file" style="width:100%"><el-option v-for="f in ['system.yaml','units.yaml','device_models.yaml','points.yaml','devices.yaml','tasks.yaml','reporting.yaml']" :label="f" :value="f"/></el-select><el-upload drag action="#" :auto-upload="false"><div>Drop YAML here or click to select</div><small>上传不会立即覆盖正式配置</small></el-upload><el-button type="primary" @click="uploaded=true">Validate & Compare</el-button></section><section v-if="uploaded"><h3>Structured Diff</h3><el-table :data="[{o:'Devices',a:'+2',r:'-1',u:'~3'},{o:'Tasks',a:'+1',r:'',u:'~2'},{o:'Point Tables',a:'',r:'',u:'~1'}]"><el-table-column prop="o" label="Object"/><el-table-column prop="a" label="Added"/><el-table-column prop="r" label="Removed"/><el-table-column prop="u" label="Updated"/></el-table><pre>{{diff}}</pre><div class="right"><el-button>Cancel</el-button><el-button>Save</el-button><el-button type="primary" @click="saveApply">Save & Apply</el-button></div></section></div></el-tab-pane><el-tab-pane label="Import Package" name="Import Package"><h3>Import Complete Configuration</h3><p>上传完整配置包，临时校验、整体 Diff 后再替换当前配置。</p><el-upload drag action="#" :auto-upload="false"><div>Drop configuration ZIP here</div></el-upload><el-button type="primary">Validate Package & Compare</el-button></el-tab-pane></el-tabs></el-card></template>

<template v-if="['Quality','Debug','Logs'].includes(menu)"><div class="head"><div><h1>{{menu}}</h1><p>沿用上一版原型，本轮未调整。</p></div></div><el-card shadow="never"><p>该页面非本轮改版重点。</p></el-card></template>
</section></main></div></template>