"""Domain model — command definitions."""

from __future__ import annotations

from datetime import UTC, datetime
from typing import Any

from pydantic import BaseModel, Field


class Command(BaseModel):
    """A write instruction issued to a device.

    ``command_id`` is the **idempotency key** — callers generate a UUID
    per logical operation.  If the same ``command_id`` is replayed the
    engine deduplicates it.
    """

    command_id: str
    """Idempotency key — a UUID generated by the caller."""

    device_id: str
    """Target device identifier."""

    point_id: str
    """Target point identifier within the device."""

    value: Any
    """Value to write — type must match the point table definition."""

    timeout: float = 5.0
    """Maximum wait time in seconds for the write to complete."""

    issued_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    """UTC timestamp when the command was issued."""


class CommandResult(BaseModel):
    """Outcome of executing a single Command."""

    command_id: str
    """Echoes the `command_id` of the originating Command."""

    success: bool
    """``True`` if the write was acknowledged by the device."""

    error: str | None = None
    """Human-readable failure reason when ``success`` is ``False``."""

    finished_at: datetime = Field(default_factory=lambda: datetime.now(UTC))
    """UTC timestamp when execution completed (success or failure)."""
