"""兼容 Collector 旧导入路径；Sink 契约的唯一实现在 Core。"""

from core.application.sink_config import (
    DatabaseSinkConnection,
    FileSinkConnection,
    IEC104SinkAddress,
    IEC104SinkConnection,
    KafkaSinkConnection,
    MODBUS_WORD_WIDTH,
    ModbusSinkAddress,
    ModbusSinkConnection,
    OPCUASinkAddress,
    OPCUASinkConnection,
    ResolvedSinkConfig,
    ResolvedSinkPoint,
    SINK_DATA_TYPES,
    SINK_NUMERIC_DATA_TYPES,
    SINK_TYPES,
    SinkAddress,
    SinkConfig,
    SinkPoint,
    SinksConfig,
    SinkSource,
    StreamSinkAddress,
)
__all__ = [
    "SINK_TYPES",
    "SINK_DATA_TYPES",
    "SINK_NUMERIC_DATA_TYPES",
    "MODBUS_WORD_WIDTH",
    "SinkSource",
    "FileSinkConnection",
    "KafkaSinkConnection",
    "DatabaseSinkConnection",
    "IEC104SinkConnection",
    "OPCUASinkConnection",
    "ModbusSinkConnection",
    "StreamSinkAddress",
    "IEC104SinkAddress",
    "OPCUASinkAddress",
    "ModbusSinkAddress",
    "SinkAddress",
    "SinkPoint",
    "ResolvedSinkPoint",
    "SinkConfig",
    "ResolvedSinkConfig",
    "SinksConfig",
]
