"""IEC 60870-5-104 codec — APCI / ASDU / information-object encode and decode.

Pure data transformation layer — no network IO, no asyncio, no state machine.
"""

from wind_hub.adapter.outbound.protocol.iec104.codec.apci import (
    APDUFrame,
    IFrame,
    SFrame,
    UFrame,
    decode_apdu,
    encode_apdu,
    encode_i_frame,
    encode_s_frame,
    encode_u_frame,
)
from wind_hub.adapter.outbound.protocol.iec104.codec.asdu import (
    ASDU,
    decode_asdu,
    encode_asdu,
)
from wind_hub.adapter.outbound.protocol.iec104.codec.info_objects import (
    CounterInterrogationCommand,
    DoubleCommand,
    DoublePoint,
    DoublePointWithTime,
    InterrogationCommand,
    MeasuredValueNormalized,
    MeasuredValueNormalizedWithTime,
    MeasuredValueScaled,
    MeasuredValueShort,
    MeasuredValueShortWithTime,
    SetpointCommandShort,
    SingleCommand,
    SinglePoint,
    SinglePointWithTime,
    decode_c_ci_na_1,
    decode_c_dc_na_1,
    decode_c_ic_na_1,
    decode_c_sc_na_1,
    decode_c_se_nc_1,
    decode_m_dp_na_1,
    decode_m_dp_tb_1,
    decode_m_me_na_1,
    decode_m_me_nb_1,
    decode_m_me_nc_1,
    decode_m_me_td_1,
    decode_m_me_tf_1,
    decode_m_sp_na_1,
    decode_m_sp_tb_1,
    encode_c_ci_na_1,
    encode_c_dc_na_1,
    encode_c_ic_na_1,
    encode_c_sc_na_1,
    encode_c_se_nc_1,
    encode_m_dp_na_1,
    encode_m_dp_tb_1,
    encode_m_me_na_1,
    encode_m_me_nb_1,
    encode_m_me_nc_1,
    encode_m_me_td_1,
    encode_m_me_tf_1,
    encode_m_sp_na_1,
    encode_m_sp_tb_1,
)
from wind_hub.adapter.outbound.protocol.iec104.codec.ioa import decode_ioa, encode_ioa
from wind_hub.adapter.outbound.protocol.iec104.codec.time import (
    CP56Time2a,
    decode_cp56time2a,
    encode_cp56time2a,
    from_datetime,
    to_datetime,
)
from wind_hub.adapter.outbound.protocol.iec104.codec.types import (
    CauseOfTransmission,
    QualityFlag,
    TypeID,
    UFrameType,
)

__all__ = [
    # types
    "TypeID",
    "CauseOfTransmission",
    "UFrameType",
    "QualityFlag",
    # IOA
    "encode_ioa",
    "decode_ioa",
    # time
    "CP56Time2a",
    "encode_cp56time2a",
    "decode_cp56time2a",
    "from_datetime",
    "to_datetime",
    # info object models
    "SinglePoint",
    "SinglePointWithTime",
    "DoublePoint",
    "DoublePointWithTime",
    "MeasuredValueNormalized",
    "MeasuredValueNormalizedWithTime",
    "MeasuredValueScaled",
    "MeasuredValueShort",
    "MeasuredValueShortWithTime",
    "SingleCommand",
    "DoubleCommand",
    "SetpointCommandShort",
    "InterrogationCommand",
    "CounterInterrogationCommand",
    # info object codecs
    "decode_m_sp_na_1",
    "encode_m_sp_na_1",
    "decode_m_sp_tb_1",
    "encode_m_sp_tb_1",
    "decode_m_dp_na_1",
    "encode_m_dp_na_1",
    "decode_m_dp_tb_1",
    "encode_m_dp_tb_1",
    "decode_m_me_na_1",
    "encode_m_me_na_1",
    "decode_m_me_nb_1",
    "encode_m_me_nb_1",
    "decode_m_me_nc_1",
    "encode_m_me_nc_1",
    "decode_m_me_td_1",
    "encode_m_me_td_1",
    "decode_m_me_tf_1",
    "encode_m_me_tf_1",
    "decode_c_sc_na_1",
    "encode_c_sc_na_1",
    "decode_c_dc_na_1",
    "encode_c_dc_na_1",
    "decode_c_se_nc_1",
    "encode_c_se_nc_1",
    "decode_c_ic_na_1",
    "encode_c_ic_na_1",
    "decode_c_ci_na_1",
    "encode_c_ci_na_1",
    # ASDU
    "ASDU",
    "decode_asdu",
    "encode_asdu",
    # APCI
    "APDUFrame",
    "IFrame",
    "SFrame",
    "UFrame",
    "decode_apdu",
    "encode_apdu",
    "encode_i_frame",
    "encode_s_frame",
    "encode_u_frame",
]
