"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

from collections import abc as _abc
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import timestamp_pb2 as _timestamp_pb2
from google.protobuf import wrappers_pb2 as _wrappers_pb2
from google.protobuf.internal import containers as _containers
import builtins as _builtins
import sys
import typing as _typing

if sys.version_info >= (3, 11):
    from typing import TypeAlias as _TypeAlias, Never as _Never
else:
    from typing_extensions import TypeAlias as _TypeAlias, Never as _Never

DESCRIPTOR: _descriptor.FileDescriptor

@_typing.final
class CollectorInfoResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COMPONENT_FIELD_NUMBER: _builtins.int
    COLLECTOR_ID_FIELD_NUMBER: _builtins.int
    BOOT_ID_FIELD_NUMBER: _builtins.int
    CONFIG_HASH_FIELD_NUMBER: _builtins.int
    ACTIVE_CONFIG_HASH_FIELD_NUMBER: _builtins.int
    PREPARED_CONFIG_HASH_FIELD_NUMBER: _builtins.int
    BOOT_CONFIG_HASH_FIELD_NUMBER: _builtins.int
    CONFIG_REVISION_FIELD_NUMBER: _builtins.int
    ACTIVE_REVISION_FIELD_NUMBER: _builtins.int
    PREPARED_REVISION_FIELD_NUMBER: _builtins.int
    RUNTIME_RUNNING_FIELD_NUMBER: _builtins.int
    component: _builtins.str
    collector_id: _builtins.str
    boot_id: _builtins.str
    config_hash: _builtins.str
    active_config_hash: _builtins.str
    prepared_config_hash: _builtins.str
    boot_config_hash: _builtins.str
    config_revision: _builtins.str
    active_revision: _builtins.str
    prepared_revision: _builtins.str
    runtime_running: _builtins.bool
    def __init__(
        self,
        *,
        component: _builtins.str = ...,
        collector_id: _builtins.str = ...,
        boot_id: _builtins.str = ...,
        config_hash: _builtins.str = ...,
        active_config_hash: _builtins.str = ...,
        prepared_config_hash: _builtins.str = ...,
        boot_config_hash: _builtins.str = ...,
        config_revision: _builtins.str = ...,
        active_revision: _builtins.str = ...,
        prepared_revision: _builtins.str = ...,
        runtime_running: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_config_hash", b"active_config_hash", "active_revision", b"active_revision", "boot_config_hash", b"boot_config_hash", "boot_id", b"boot_id", "collector_id", b"collector_id", "component", b"component", "config_hash", b"config_hash", "config_revision", b"config_revision", "prepared_config_hash", b"prepared_config_hash", "prepared_revision", b"prepared_revision", "runtime_running", b"runtime_running"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___CollectorInfoResponse: _TypeAlias = CollectorInfoResponse  # noqa: Y015

@_typing.final
class AcquisitionInfoMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSTANCE_ID_FIELD_NUMBER: _builtins.int
    TASK_ID_FIELD_NUMBER: _builtins.int
    DEVICE_ID_FIELD_NUMBER: _builtins.int
    POINT_GROUP_FIELD_NUMBER: _builtins.int
    RUNNING_FIELD_NUMBER: _builtins.int
    CONSECUTIVE_FAILURES_FIELD_NUMBER: _builtins.int
    LAST_ERROR_FIELD_NUMBER: _builtins.int
    LAST_DURATION_FIELD_NUMBER: _builtins.int
    instance_id: _builtins.str
    task_id: _builtins.str
    device_id: _builtins.str
    point_group: _builtins.str
    running: _builtins.bool
    consecutive_failures: _builtins.int
    last_error: _builtins.str
    @_builtins.property
    def last_duration(self) -> _wrappers_pb2.DoubleValue: ...
    def __init__(
        self,
        *,
        instance_id: _builtins.str = ...,
        task_id: _builtins.str = ...,
        device_id: _builtins.str = ...,
        point_group: _builtins.str = ...,
        running: _builtins.bool = ...,
        consecutive_failures: _builtins.int = ...,
        last_error: _builtins.str = ...,
        last_duration: _wrappers_pb2.DoubleValue | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["last_duration", b"last_duration"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["consecutive_failures", b"consecutive_failures", "device_id", b"device_id", "instance_id", b"instance_id", "last_duration", b"last_duration", "last_error", b"last_error", "point_group", b"point_group", "running", b"running", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AcquisitionInfoMessage: _TypeAlias = AcquisitionInfoMessage  # noqa: Y015

@_typing.final
class RuntimeStatusResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    RUNNING_FIELD_NUMBER: _builtins.int
    DEVICE_COUNT_FIELD_NUMBER: _builtins.int
    SINK_COUNT_FIELD_NUMBER: _builtins.int
    DEVICES_CONNECTED_FIELD_NUMBER: _builtins.int
    SINKS_HEALTHY_FIELD_NUMBER: _builtins.int
    POINTS_COLLECTED_FIELD_NUMBER: _builtins.int
    POINTS_ROUTED_FIELD_NUMBER: _builtins.int
    POINTS_DROPPED_FIELD_NUMBER: _builtins.int
    ACQUISITIONS_FIELD_NUMBER: _builtins.int
    running: _builtins.bool
    device_count: _builtins.int
    sink_count: _builtins.int
    devices_connected: _builtins.int
    sinks_healthy: _builtins.int
    points_collected: _builtins.int
    points_routed: _builtins.int
    points_dropped: _builtins.int
    @_builtins.property
    def acquisitions(self) -> _containers.RepeatedCompositeFieldContainer[Global___AcquisitionInfoMessage]: ...
    def __init__(
        self,
        *,
        running: _builtins.bool = ...,
        device_count: _builtins.int = ...,
        sink_count: _builtins.int = ...,
        devices_connected: _builtins.int = ...,
        sinks_healthy: _builtins.int = ...,
        points_collected: _builtins.int = ...,
        points_routed: _builtins.int = ...,
        points_dropped: _builtins.int = ...,
        acquisitions: _abc.Iterable[Global___AcquisitionInfoMessage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acquisitions", b"acquisitions", "device_count", b"device_count", "devices_connected", b"devices_connected", "points_collected", b"points_collected", "points_dropped", b"points_dropped", "points_routed", b"points_routed", "running", b"running", "sink_count", b"sink_count", "sinks_healthy", b"sinks_healthy"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___RuntimeStatusResponse: _TypeAlias = RuntimeStatusResponse  # noqa: Y015

@_typing.final
class MetricsCounters(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    POINTS_TOTAL_FIELD_NUMBER: _builtins.int
    POINTS_BAD_FIELD_NUMBER: _builtins.int
    ACQUISITION_RUNS_FIELD_NUMBER: _builtins.int
    ACQUISITION_FAILURES_FIELD_NUMBER: _builtins.int
    ACQUISITION_PARTIAL_FIELD_NUMBER: _builtins.int
    MISSED_CYCLES_FIELD_NUMBER: _builtins.int
    POLL_OVERRUNS_FIELD_NUMBER: _builtins.int
    CONNECT_FAILURES_FIELD_NUMBER: _builtins.int
    RECONNECTS_FIELD_NUMBER: _builtins.int
    points_total: _builtins.int
    points_bad: _builtins.int
    acquisition_runs: _builtins.int
    acquisition_failures: _builtins.int
    acquisition_partial: _builtins.int
    missed_cycles: _builtins.int
    poll_overruns: _builtins.int
    connect_failures: _builtins.int
    reconnects: _builtins.int
    def __init__(
        self,
        *,
        points_total: _builtins.int = ...,
        points_bad: _builtins.int = ...,
        acquisition_runs: _builtins.int = ...,
        acquisition_failures: _builtins.int = ...,
        acquisition_partial: _builtins.int = ...,
        missed_cycles: _builtins.int = ...,
        poll_overruns: _builtins.int = ...,
        connect_failures: _builtins.int = ...,
        reconnects: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["acquisition_failures", b"acquisition_failures", "acquisition_partial", b"acquisition_partial", "acquisition_runs", b"acquisition_runs", "connect_failures", b"connect_failures", "missed_cycles", b"missed_cycles", "points_bad", b"points_bad", "points_total", b"points_total", "poll_overruns", b"poll_overruns", "reconnects", b"reconnects"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MetricsCounters: _TypeAlias = MetricsCounters  # noqa: Y015

@_typing.final
class StringCounter(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    KEY_FIELD_NUMBER: _builtins.int
    VALUE_FIELD_NUMBER: _builtins.int
    key: _builtins.str
    value: _builtins.int
    def __init__(
        self,
        *,
        key: _builtins.str = ...,
        value: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["key", b"key", "value", b"value"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___StringCounter: _TypeAlias = StringCounter  # noqa: Y015

@_typing.final
class MetricsEvent(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TIMESTAMP_FIELD_NUMBER: _builtins.int
    KIND_FIELD_NUMBER: _builtins.int
    OBJECT_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    kind: _builtins.str
    object: _builtins.str
    message: _builtins.str
    @_builtins.property
    def timestamp(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        timestamp: _timestamp_pb2.Timestamp | None = ...,
        kind: _builtins.str = ...,
        object: _builtins.str = ...,
        message: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["timestamp", b"timestamp"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["kind", b"kind", "message", b"message", "object", b"object", "timestamp", b"timestamp"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MetricsEvent: _TypeAlias = MetricsEvent  # noqa: Y015

@_typing.final
class MetricsSnapshotResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    COUNTERS_FIELD_NUMBER: _builtins.int
    DEVICE_CONNECT_FAILURES_FIELD_NUMBER: _builtins.int
    DEVICE_RECONNECTS_FIELD_NUMBER: _builtins.int
    EVENTS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def counters(self) -> Global___MetricsCounters: ...
    @_builtins.property
    def device_connect_failures(self) -> _containers.RepeatedCompositeFieldContainer[Global___StringCounter]: ...
    @_builtins.property
    def device_reconnects(self) -> _containers.RepeatedCompositeFieldContainer[Global___StringCounter]: ...
    @_builtins.property
    def events(self) -> _containers.RepeatedCompositeFieldContainer[Global___MetricsEvent]: ...
    def __init__(
        self,
        *,
        counters: Global___MetricsCounters | None = ...,
        device_connect_failures: _abc.Iterable[Global___StringCounter] | None = ...,
        device_reconnects: _abc.Iterable[Global___StringCounter] | None = ...,
        events: _abc.Iterable[Global___MetricsEvent] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["counters", b"counters"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["counters", b"counters", "device_connect_failures", b"device_connect_failures", "device_reconnects", b"device_reconnects", "events", b"events"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___MetricsSnapshotResponse: _TypeAlias = MetricsSnapshotResponse  # noqa: Y015

@_typing.final
class TaskSummaryMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    DEVICE_FIELD_NUMBER: _builtins.int
    DEVICE_GROUP_FIELD_NUMBER: _builtins.int
    POINT_GROUP_FIELD_NUMBER: _builtins.int
    INTERVAL_FIELD_NUMBER: _builtins.int
    TARGETS_FIELD_NUMBER: _builtins.int
    ENABLED_FIELD_NUMBER: _builtins.int
    RUNTIME_STATE_FIELD_NUMBER: _builtins.int
    INSTANCE_COUNT_FIELD_NUMBER: _builtins.int
    RUNNING_INSTANCES_FIELD_NUMBER: _builtins.int
    STOPPED_INSTANCES_FIELD_NUMBER: _builtins.int
    FAILED_INSTANCES_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    point_group: _builtins.str
    enabled: _builtins.bool
    runtime_state: _builtins.str
    instance_count: _builtins.int
    running_instances: _builtins.int
    stopped_instances: _builtins.int
    failed_instances: _builtins.int
    @_builtins.property
    def device(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def device_group(self) -> _wrappers_pb2.StringValue: ...
    @_builtins.property
    def interval(self) -> _wrappers_pb2.DoubleValue: ...
    @_builtins.property
    def targets(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        device: _wrappers_pb2.StringValue | None = ...,
        device_group: _wrappers_pb2.StringValue | None = ...,
        point_group: _builtins.str = ...,
        interval: _wrappers_pb2.DoubleValue | None = ...,
        targets: _abc.Iterable[_builtins.str] | None = ...,
        enabled: _builtins.bool = ...,
        runtime_state: _builtins.str = ...,
        instance_count: _builtins.int = ...,
        running_instances: _builtins.int = ...,
        stopped_instances: _builtins.int = ...,
        failed_instances: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "device_group", b"device_group", "interval", b"interval"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device", b"device", "device_group", b"device_group", "enabled", b"enabled", "failed_instances", b"failed_instances", "instance_count", b"instance_count", "interval", b"interval", "point_group", b"point_group", "running_instances", b"running_instances", "runtime_state", b"runtime_state", "stopped_instances", b"stopped_instances", "targets", b"targets", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskSummaryMessage: _TypeAlias = TaskSummaryMessage  # noqa: Y015

@_typing.final
class TaskInstanceMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSTANCE_ID_FIELD_NUMBER: _builtins.int
    TASK_ID_FIELD_NUMBER: _builtins.int
    DEVICE_ID_FIELD_NUMBER: _builtins.int
    POINT_GROUP_FIELD_NUMBER: _builtins.int
    INTERVAL_FIELD_NUMBER: _builtins.int
    TARGETS_FIELD_NUMBER: _builtins.int
    STATE_FIELD_NUMBER: _builtins.int
    instance_id: _builtins.str
    task_id: _builtins.str
    device_id: _builtins.str
    point_group: _builtins.str
    state: _builtins.str
    @_builtins.property
    def interval(self) -> _wrappers_pb2.DoubleValue: ...
    @_builtins.property
    def targets(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        instance_id: _builtins.str = ...,
        task_id: _builtins.str = ...,
        device_id: _builtins.str = ...,
        point_group: _builtins.str = ...,
        interval: _wrappers_pb2.DoubleValue | None = ...,
        targets: _abc.Iterable[_builtins.str] | None = ...,
        state: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["interval", b"interval"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["device_id", b"device_id", "instance_id", b"instance_id", "interval", b"interval", "point_group", b"point_group", "state", b"state", "targets", b"targets", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskInstanceMessage: _TypeAlias = TaskInstanceMessage  # noqa: Y015

@_typing.final
class ListTasksResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___TaskSummaryMessage]: ...
    def __init__(
        self,
        *,
        items: _abc.Iterable[Global___TaskSummaryMessage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListTasksResponse: _TypeAlias = ListTasksResponse  # noqa: Y015

@_typing.final
class ListTaskInstancesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___TaskInstanceMessage]: ...
    def __init__(
        self,
        *,
        items: _abc.Iterable[Global___TaskInstanceMessage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListTaskInstancesResponse: _TypeAlias = ListTaskInstancesResponse  # noqa: Y015

@_typing.final
class TaskIdRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskIdRequest: _TypeAlias = TaskIdRequest  # noqa: Y015

@_typing.final
class InstanceIdRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSTANCE_ID_FIELD_NUMBER: _builtins.int
    instance_id: _builtins.str
    def __init__(
        self,
        *,
        instance_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["instance_id", b"instance_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___InstanceIdRequest: _TypeAlias = InstanceIdRequest  # noqa: Y015

@_typing.final
class TaskStartRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    TASK_ID_FIELD_NUMBER: _builtins.int
    PLACEMENT_GENERATION_FIELD_NUMBER: _builtins.int
    task_id: _builtins.str
    placement_generation: _builtins.int
    def __init__(
        self,
        *,
        task_id: _builtins.str = ...,
        placement_generation: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["placement_generation", b"placement_generation", "task_id", b"task_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskStartRequest: _TypeAlias = TaskStartRequest  # noqa: Y015

@_typing.final
class TaskInstanceStartRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    INSTANCE_ID_FIELD_NUMBER: _builtins.int
    PLACEMENT_GENERATION_FIELD_NUMBER: _builtins.int
    instance_id: _builtins.str
    placement_generation: _builtins.int
    def __init__(
        self,
        *,
        instance_id: _builtins.str = ...,
        placement_generation: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["instance_id", b"instance_id", "placement_generation", b"placement_generation"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskInstanceStartRequest: _TypeAlias = TaskInstanceStartRequest  # noqa: Y015

@_typing.final
class TaskPlacementSnapshotRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    WORKER_ID_FIELD_NUMBER: _builtins.int
    GENERATION_FIELD_NUMBER: _builtins.int
    TASK_IDS_FIELD_NUMBER: _builtins.int
    worker_id: _builtins.str
    generation: _builtins.int
    @_builtins.property
    def task_ids(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        worker_id: _builtins.str = ...,
        generation: _builtins.int = ...,
        task_ids: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["generation", b"generation", "task_ids", b"task_ids", "worker_id", b"worker_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskPlacementSnapshotRequest: _TypeAlias = TaskPlacementSnapshotRequest  # noqa: Y015

@_typing.final
class TaskPlacementSnapshotResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    GENERATION_FIELD_NUMBER: _builtins.int
    TASK_COUNT_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    generation: _builtins.int
    task_count: _builtins.int
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        generation: _builtins.int = ...,
        task_count: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["generation", b"generation", "success", b"success", "task_count", b"task_count"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskPlacementSnapshotResponse: _TypeAlias = TaskPlacementSnapshotResponse  # noqa: Y015

@_typing.final
class DeviceInfoMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICE_ID_FIELD_NUMBER: _builtins.int
    PROTOCOL_FIELD_NUMBER: _builtins.int
    CONNECTED_FIELD_NUMBER: _builtins.int
    LAST_SEEN_FIELD_NUMBER: _builtins.int
    CONSECUTIVE_FAILURES_FIELD_NUMBER: _builtins.int
    LAST_ERROR_FIELD_NUMBER: _builtins.int
    device_id: _builtins.str
    protocol: _builtins.str
    connected: _builtins.bool
    consecutive_failures: _builtins.int
    last_error: _builtins.str
    @_builtins.property
    def last_seen(self) -> _timestamp_pb2.Timestamp: ...
    def __init__(
        self,
        *,
        device_id: _builtins.str = ...,
        protocol: _builtins.str = ...,
        connected: _builtins.bool = ...,
        last_seen: _timestamp_pb2.Timestamp | None = ...,
        consecutive_failures: _builtins.int = ...,
        last_error: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["last_seen", b"last_seen"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["connected", b"connected", "consecutive_failures", b"consecutive_failures", "device_id", b"device_id", "last_error", b"last_error", "last_seen", b"last_seen", "protocol", b"protocol"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceInfoMessage: _TypeAlias = DeviceInfoMessage  # noqa: Y015

@_typing.final
class ListDevicesResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___DeviceInfoMessage]: ...
    def __init__(
        self,
        *,
        items: _abc.Iterable[Global___DeviceInfoMessage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListDevicesResponse: _TypeAlias = ListDevicesResponse  # noqa: Y015

@_typing.final
class SinkInfoMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    HEALTHY_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    QUEUE_DEPTH_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    healthy: _builtins.bool
    message: _builtins.str
    queue_depth: _builtins.int
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
        healthy: _builtins.bool = ...,
        message: _builtins.str = ...,
        queue_depth: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["healthy", b"healthy", "message", b"message", "name", b"name", "queue_depth", b"queue_depth"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SinkInfoMessage: _TypeAlias = SinkInfoMessage  # noqa: Y015

@_typing.final
class ListSinksResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ITEMS_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def items(self) -> _containers.RepeatedCompositeFieldContainer[Global___SinkInfoMessage]: ...
    def __init__(
        self,
        *,
        items: _abc.Iterable[Global___SinkInfoMessage] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["items", b"items"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ListSinksResponse: _TypeAlias = ListSinksResponse  # noqa: Y015

@_typing.final
class SinkRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    NAME_FIELD_NUMBER: _builtins.int
    name: _builtins.str
    def __init__(
        self,
        *,
        name: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["name", b"name"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SinkRequest: _TypeAlias = SinkRequest  # noqa: Y015

@_typing.final
class SinkOperationResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    MESSAGE_FIELD_NUMBER: _builtins.int
    QUEUE_DEPTH_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    message: _builtins.str
    queue_depth: _builtins.int
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        message: _builtins.str = ...,
        queue_depth: _builtins.int = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["message", b"message", "queue_depth", b"queue_depth", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SinkOperationResponse: _TypeAlias = SinkOperationResponse  # noqa: Y015

@_typing.final
class DeviceDiffMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDED_FIELD_NUMBER: _builtins.int
    REMOVED_FIELD_NUMBER: _builtins.int
    UPDATED_FIELD_NUMBER: _builtins.int
    UNCHANGED_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def added(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def removed(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def updated(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def unchanged(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        added: _abc.Iterable[_builtins.str] | None = ...,
        removed: _abc.Iterable[_builtins.str] | None = ...,
        updated: _abc.Iterable[_builtins.str] | None = ...,
        unchanged: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["added", b"added", "removed", b"removed", "unchanged", b"unchanged", "updated", b"updated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___DeviceDiffMessage: _TypeAlias = DeviceDiffMessage  # noqa: Y015

@_typing.final
class SinkDiffMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDED_FIELD_NUMBER: _builtins.int
    REMOVED_FIELD_NUMBER: _builtins.int
    UPDATED_FIELD_NUMBER: _builtins.int
    UNCHANGED_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def added(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def removed(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def updated(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def unchanged(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        added: _abc.Iterable[_builtins.str] | None = ...,
        removed: _abc.Iterable[_builtins.str] | None = ...,
        updated: _abc.Iterable[_builtins.str] | None = ...,
        unchanged: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["added", b"added", "removed", b"removed", "unchanged", b"unchanged", "updated", b"updated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___SinkDiffMessage: _TypeAlias = SinkDiffMessage  # noqa: Y015

@_typing.final
class TaskDiffMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    ADDED_FIELD_NUMBER: _builtins.int
    REMOVED_FIELD_NUMBER: _builtins.int
    UPDATED_FIELD_NUMBER: _builtins.int
    UNCHANGED_FIELD_NUMBER: _builtins.int
    @_builtins.property
    def added(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def removed(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def updated(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    @_builtins.property
    def unchanged(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        added: _abc.Iterable[_builtins.str] | None = ...,
        removed: _abc.Iterable[_builtins.str] | None = ...,
        updated: _abc.Iterable[_builtins.str] | None = ...,
        unchanged: _abc.Iterable[_builtins.str] | None = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["added", b"added", "removed", b"removed", "unchanged", b"unchanged", "updated", b"updated"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___TaskDiffMessage: _TypeAlias = TaskDiffMessage  # noqa: Y015

@_typing.final
class ConfigDiffMessage(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    DEVICES_FIELD_NUMBER: _builtins.int
    SINKS_FIELD_NUMBER: _builtins.int
    TASKS_FIELD_NUMBER: _builtins.int
    POINTS_CHANGED_FIELD_NUMBER: _builtins.int
    POINT_TABLES_CHANGED_FIELD_NUMBER: _builtins.int
    UNITS_CHANGED_FIELD_NUMBER: _builtins.int
    points_changed: _builtins.bool
    units_changed: _builtins.bool
    @_builtins.property
    def devices(self) -> Global___DeviceDiffMessage: ...
    @_builtins.property
    def sinks(self) -> Global___SinkDiffMessage: ...
    @_builtins.property
    def tasks(self) -> Global___TaskDiffMessage: ...
    @_builtins.property
    def point_tables_changed(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        devices: Global___DeviceDiffMessage | None = ...,
        sinks: Global___SinkDiffMessage | None = ...,
        tasks: Global___TaskDiffMessage | None = ...,
        points_changed: _builtins.bool = ...,
        point_tables_changed: _abc.Iterable[_builtins.str] | None = ...,
        units_changed: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["devices", b"devices", "sinks", b"sinks", "tasks", b"tasks"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["devices", b"devices", "point_tables_changed", b"point_tables_changed", "points_changed", b"points_changed", "sinks", b"sinks", "tasks", b"tasks", "units_changed", b"units_changed"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ConfigDiffMessage: _TypeAlias = ConfigDiffMessage  # noqa: Y015

@_typing.final
class PrepareConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REVISION_ID_FIELD_NUMBER: _builtins.int
    CONFIG_HASH_FIELD_NUMBER: _builtins.int
    FORCE_RECONFIGURE_FIELD_NUMBER: _builtins.int
    revision_id: _builtins.str
    config_hash: _builtins.str
    force_reconfigure: _builtins.bool
    def __init__(
        self,
        *,
        revision_id: _builtins.str = ...,
        config_hash: _builtins.str = ...,
        force_reconfigure: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_hash", b"config_hash", "force_reconfigure", b"force_reconfigure", "revision_id", b"revision_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PrepareConfigRequest: _TypeAlias = PrepareConfigRequest  # noqa: Y015

@_typing.final
class PrepareConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    REVISION_ID_FIELD_NUMBER: _builtins.int
    CONFIG_HASH_FIELD_NUMBER: _builtins.int
    DIFF_FIELD_NUMBER: _builtins.int
    ERRORS_FIELD_NUMBER: _builtins.int
    DURATION_MS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    revision_id: _builtins.str
    config_hash: _builtins.str
    duration_ms: _builtins.float
    @_builtins.property
    def diff(self) -> Global___ConfigDiffMessage: ...
    @_builtins.property
    def errors(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        revision_id: _builtins.str = ...,
        config_hash: _builtins.str = ...,
        diff: Global___ConfigDiffMessage | None = ...,
        errors: _abc.Iterable[_builtins.str] | None = ...,
        duration_ms: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["diff", b"diff"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["config_hash", b"config_hash", "diff", b"diff", "duration_ms", b"duration_ms", "errors", b"errors", "revision_id", b"revision_id", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___PrepareConfigResponse: _TypeAlias = PrepareConfigResponse  # noqa: Y015

@_typing.final
class ActivateConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REVISION_ID_FIELD_NUMBER: _builtins.int
    revision_id: _builtins.str
    def __init__(
        self,
        *,
        revision_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision_id", b"revision_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActivateConfigRequest: _TypeAlias = ActivateConfigRequest  # noqa: Y015

@_typing.final
class ActivateConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    REVISION_ID_FIELD_NUMBER: _builtins.int
    ACTIVE_CONFIG_HASH_FIELD_NUMBER: _builtins.int
    DIFF_FIELD_NUMBER: _builtins.int
    ERRORS_FIELD_NUMBER: _builtins.int
    DURATION_MS_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    revision_id: _builtins.str
    active_config_hash: _builtins.str
    duration_ms: _builtins.float
    @_builtins.property
    def diff(self) -> Global___ConfigDiffMessage: ...
    @_builtins.property
    def errors(self) -> _containers.RepeatedScalarFieldContainer[_builtins.str]: ...
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        revision_id: _builtins.str = ...,
        active_config_hash: _builtins.str = ...,
        diff: Global___ConfigDiffMessage | None = ...,
        errors: _abc.Iterable[_builtins.str] | None = ...,
        duration_ms: _builtins.float = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _typing.Literal["diff", b"diff"]  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["active_config_hash", b"active_config_hash", "diff", b"diff", "duration_ms", b"duration_ms", "errors", b"errors", "revision_id", b"revision_id", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___ActivateConfigResponse: _TypeAlias = ActivateConfigResponse  # noqa: Y015

@_typing.final
class AbortConfigRequest(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    REVISION_ID_FIELD_NUMBER: _builtins.int
    revision_id: _builtins.str
    def __init__(
        self,
        *,
        revision_id: _builtins.str = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["revision_id", b"revision_id"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AbortConfigRequest: _TypeAlias = AbortConfigRequest  # noqa: Y015

@_typing.final
class AbortConfigResponse(_message.Message):
    DESCRIPTOR: _descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: _builtins.int
    REVISION_ID_FIELD_NUMBER: _builtins.int
    ABORTED_FIELD_NUMBER: _builtins.int
    success: _builtins.bool
    revision_id: _builtins.str
    aborted: _builtins.bool
    def __init__(
        self,
        *,
        success: _builtins.bool = ...,
        revision_id: _builtins.str = ...,
        aborted: _builtins.bool = ...,
    ) -> None: ...
    _HasFieldArgType: _TypeAlias = _Never  # noqa: Y015
    def HasField(self, field_name: _HasFieldArgType) -> _builtins.bool: ...
    _ClearFieldArgType: _TypeAlias = _typing.Literal["aborted", b"aborted", "revision_id", b"revision_id", "success", b"success"]  # noqa: Y015
    def ClearField(self, field_name: _ClearFieldArgType) -> None: ...
    def WhichOneof(self, oneof_group: _Never) -> None: ...

Global___AbortConfigResponse: _TypeAlias = AbortConfigResponse  # noqa: Y015
